##### Import the libraries

In [244]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

##### Load the datasets

In [245]:
ad = pd.read_csv(r"C:\Users\balog\OneDrive\Documents\Olayemi\Intership\Hospital_Bed_Demand_Forcasting\Data\Raw\admissions_discharges.csv")
bd = pd.read_csv(r"C:\Users\balog\OneDrive\Documents\Olayemi\Intership\Hospital_Bed_Demand_Forcasting\Data\Raw\bed_inventory_occupancy.csv")
oa = pd.read_csv(r"C:\Users\balog\OneDrive\Documents\Olayemi\Intership\Hospital_Bed_Demand_Forcasting\Data\Raw\ed_outpatient_arrivals.csv")
es = pd.read_csv(r"C:\Users\balog\OneDrive\Documents\Olayemi\Intership\Hospital_Bed_Demand_Forcasting\Data\Raw\elective_surgery_schedule.csv")
hr = pd.read_csv(r"C:\Users\balog\OneDrive\Documents\Olayemi\Intership\Hospital_Bed_Demand_Forcasting\Data\Raw\hospital_reference.csv")
sr = pd.read_csv (r"C:\Users\balog\OneDrive\Documents\Olayemi\Intership\Hospital_Bed_Demand_Forcasting\Data\Raw\staffing_resource.csv")

##### Admission Discharges Dataset Overview

In [246]:
print("="*50)
print("Admission Discharges Dataset Overview")
print("="*50)

print("\nFirst 5 Rows:")
print(ad.head())

print(f"Rows: {ad.shape[0]}")
print(f"Columns: {ad.shape[1]}")
print(f"Shape: {ad.shape}")

print("\nColumn Names:")
print(ad.columns.tolist())

print("\nData Types:")
print(ad.dtypes)

print("\nMissing Values:")
print(ad.isnull().sum())

print("\nDuplicate Rows:")
print(ad.duplicated().sum())

print("\nUnique Values:")
print(ad.nunique())

for col in ad.columns:
    print(f"\n{col}")
    print(ad[col].unique())

==================================================
Admission Discharges Dataset Overview
==================================================

First 5 Rows:
  hospital_id  patient_id admission_id   admission_datetime  \
0  HHN-MAN-01  PAT0316166  ADM00063791  2024-12-03 11:59:00
1  HHN-BIR-01  PAT0292869  ADM00081326  2024-07-13 14:21:00
2  HHN-LON-02  PAT0073285  ADM00047712  2025-06-24 07:36:00
3  HHN-LON-01  PAT0262803  ADM00014431  2024-12-09 15:16:00
4  HHN-LON-02  PAT0181895  ADM00118155  2025-08-20 06:42:00

    discharge_datetime admission_type      admission_source     specialty  \
0  2024-12-06 18:35:00      Emergency  Emergency Department  Orthopaedics
1  2024-07-17 00:15:00      Emergency  Emergency Department  Orthopaedics
2  2025-06-30 14:24:00      Emergency  Emergency Department  Orthopaedics
3  2024-12-11 00:34:00      Emergency  Emergency Department  Orthopaedics
4  2025-08-24 09:08:00       Elective          Waiting List  Orthopaedics

                  ward       bed_type  length_of_stay_hours  \
0  Orthopaedics Ward B       Standard                  78.6
1  Orthopaedics Ward B       Standard                  81.9
2  Orthopaedics Ward B       Standard                 150.8
3  Orthopaedics Ward A       Standard                  33.3
4  Orthopaedics Ward A  ICU Step-down                  98.4

     discharge_destination  discharge_datetime_corrected
0   Home With Care Package                         False
1  Rehabilitation Facility                         False
2                     Home                         False
3                     Home                         False
4                     Home                         False
Rows: 130956
Columns: 13
Shape: (130956, 13)

Column Names:
['hospital_id', 'patient_id', 'admission_id', 'admission_datetime', 'discharge_datetime', 'admission_type', 'admission_source', 'specialty', 'ward', 'bed_type', 'length_of_stay_hours', 'discharge_destination', 'discharge_datetime_corrected']

Data Types:
hospital_id                      object
patient_id                       object
admission_id                     object
admission_datetime               object
discharge_datetime               object
admission_type                   object
admission_source                 object
specialty                        object
ward                             object
bed_type                         object
length_of_stay_hours            float64
discharge_destination            object
discharge_datetime_corrected       bool
dtype: object

Missing Values:
hospital_id                     0
patient_id                      0
admission_id                    0
admission_datetime              0
discharge_datetime              5
admission_type                  0
admission_source                0
specialty                       0
ward                            0
bed_type                        0
length_of_stay_hours            5
discharge_destination           0
discharge_datetime_corrected    0
dtype: int64

Duplicate Rows:
0

Unique Values:
hospital_id                          5
patient_id                      114522
admission_id                    130956
admission_datetime              121310
discharge_datetime              123025
admission_type                       3
admission_source                     2
specialty                            6
ward                                 8
bed_type                             4
length_of_stay_hours              4754
discharge_destination                7
discharge_datetime_corrected         2
dtype: int64

hospital_id
['HHN-MAN-01' 'HHN-BIR-01' 'HHN-LON-02' 'HHN-LON-01' 'HHN-EDI-01']

patient_id
['PAT0316166' 'PAT0292869' 'PAT0073285' ... 'PAT0134504' 'PAT0256084'
 'PAT0117108']

admission_id
['ADM00063791' 'ADM00081326' 'ADM00047712' ... 'ADM00113612' 'ADM00048507'
 'ADM00051442']

admission_datetime
['2024-12-03 11:59:00' '2024-07-13 14:21:00' '2025-06-24 07:36:00' ...
 '2025-11-06 07:28:00' '2025-07-28 16:35:00' '2025-11-17 12:00:00']

discharge_datetime
['2024-12-06 18:35:00' '2024-07-17 00:15:00' '2025-06-30 14:24:00' ...
 '2025-11-06 14:49:00' '2025-08-01 11:47:00' '2025-11-26 12:12:00']

admission_type
['Emergency' 'Elective' 'Transfer']

admission_source
['Emergency Department' 'Waiting List']

specialty
['Orthopaedics' 'Cardiology' 'General Medicine' 'Diagnostics' 'Oncology'
 'ICU']

ward
['Orthopaedics Ward B' 'Orthopaedics Ward A' 'Cardiology Ward'
 'General Medicine Ward B' 'General Medicine Ward A' 'Day Case Unit'
 'Oncology Ward' 'ICU']

bed_type
['Standard' 'ICU Step-down' 'Day Case' 'Critical Care']

length_of_stay_hours
[ 78.6         81.9        150.8        ...  77.51666667 409.3
 508.3       ]

discharge_destination
['Home With Care Package' 'Rehabilitation Facility' 'Home' 'Deceased'
 'Care Home' 'Transfer To Another Hospital' 'Not Recorded']

discharge_datetime_corrected
[False  True]

In [247]:
ad[ad["discharge_datetime"] < ad["admission_datetime"]].shape[0]

0

In [248]:
ad[ad["discharge_datetime"].isna()]

,hospital_id,patient_id,admission_id,admission_datetime,discharge_datetime,admission_type,admission_source,specialty,ward,bed_type,length_of_stay_hours,discharge_destination,discharge_datetime_corrected
70492,HHN-MAN-01,PAT0215702,ADM00059043,2024-06-23 03:21:00,NaN,Emergency,Emergency Department,General Medicine,General Medicine Ward A,Standard,NaN,Home With Care Package,False
86543,HHN-MAN-01,PAT0217827,ADM00066764,2025-02-16 22:53:00,NaN,Emergency,Emergency Department,General Medicine,General Medicine Ward A,Standard,NaN,Home,False
103201,HHN-LON-02,PAT0162806,ADM00051414,2025-11-19 09:38:00,NaN,Emergency,Emergency Department,General Medicine,General Medicine Ward B,Standard,NaN,Home,False
110602,HHN-LON-01,PAT0468083,ADM00020115,2025-03-25 11:41:00,NaN,Emergency,Emergency Department,Cardiology,Cardiology Ward,Standard,NaN,Not Recorded,False
117930,HHN-MAN-01,PAT0100682,ADM00067048,2025-02-25 06:32:00,NaN,Emergency,Emergency Department,General Medicine,General Medicine Ward A,Standard,NaN,Home,False

In [249]:
# Convert the admission and discharge datetime columns to datetime format
ad["admission_datetime"] = pd.to_datetime(ad["admission_datetime"])
ad["discharge_datetime"] = pd.to_datetime(ad["discharge_datetime"])

##### Bed Inventory Dataset Overview

In [250]:
print("="*50)
print("Bed Inventory Dataset Overview")
print("="*50)

print("\nFirst 5 Rows:")
print(bd.head())

print(f"Rows: {bd.shape[0]}")
print(f"Columns: {bd.shape[1]}")
print(f"Shape: {bd.shape}")

print("\nColumn Names:")
print(bd.columns.tolist())

print("\nData Types:")
print(bd.dtypes)

print("\nMissing Values:")
print(bd.isnull().sum())

print("\nDuplicate Rows:")
print(bd.duplicated().sum())

print("\nUnique Values:")
print(bd.nunique())

for col in bd.columns:
    print(f"\n{col}")
    print(bd[col].unique())

==================================================
Bed Inventory Dataset Overview
==================================================

First 5 Rows:
              datetime hospital_id             ward  bed_type  total_beds  \
0  2024-01-01 00:00:00  HHN-BIR-01  Cardiology Ward  Standard          42
1  2024-01-01 01:00:00  HHN-BIR-01  Cardiology Ward  Standard          42
2  2024-01-01 02:00:00  HHN-BIR-01  Cardiology Ward  Standard          42
3  2024-01-01 03:00:00  HHN-BIR-01  Cardiology Ward  Standard          42
4  2024-01-01 04:00:00  HHN-BIR-01  Cardiology Ward  Standard          42

   staffed_beds  occupied_beds  closed_beds  occupancy_rate
0            42              0            0             0.0
1            42              0            0             0.0
2            42              0            0             0.0
3            42              0            0             0.0
4            42              0            0             0.0
Rows: 701760
Columns: 9
Shape: (701760, 9)

Column Names:
['datetime', 'hospital_id', 'ward', 'bed_type', 'total_beds', 'staffed_beds', 'occupied_beds', 'closed_beds', 'occupancy_rate']

Data Types:
datetime           object
hospital_id        object
ward               object
bed_type           object
total_beds          int64
staffed_beds        int64
occupied_beds       int64
closed_beds         int64
occupancy_rate    float64
dtype: object

Missing Values:
datetime          0
hospital_id       0
ward              0
bed_type          0
total_beds        0
staffed_beds      0
occupied_beds     0
closed_beds       0
occupancy_rate    0
dtype: int64

Duplicate Rows:
0

Unique Values:
datetime          17544
hospital_id           5
ward                  8
bed_type              3
total_beds           20
staffed_beds         48
occupied_beds        47
closed_beds           9
occupancy_rate      635
dtype: int64

datetime
['2024-01-01 00:00:00' '2024-01-01 01:00:00' '2024-01-01 02:00:00' ...
 '2025-12-31 21:00:00' '2025-12-31 22:00:00' '2025-12-31 23:00:00']

hospital_id
['HHN-BIR-01' 'HHN-EDI-01' 'HHN-LON-01' 'HHN-LON-02' 'HHN-MAN-01']

ward
['Cardiology Ward' 'Day Case Unit' 'General Medicine Ward A'
 'General Medicine Ward B' 'ICU' 'Oncology Ward' 'Orthopaedics Ward A'
 'Orthopaedics Ward B']

bed_type
['Standard' 'Day Case' 'Critical Care']

total_beds
[42  3 16  9 18 11 17  8 13 10 38  4 35 28 12 58 24 21 20 32]

staffed_beds
[42 41 39 37 36 40 38  3  2 14 16 15  9  8 18 17 11 10  7 13 12 34 35 33
  4 31 32 30 28 24 25 27 26 58 55 56 50 51 57 52 53 54 21 23 22 19 20 29]

occupied_beds
[ 0  1  2  4  5  6  7  8  9 10 11 13 14 15 16 17 18 19 20 21 22 23 24 25
 28 29 27 26 30 32 31 34 33 35 36 39 38 40 41 37 12 42  3 43 44 45 46]

closed_beds
[0 2 7 5 1 3 6 4 8]

occupancy_rate
[0.         0.02380952 0.02439024 0.04761905 0.0952381  0.11904762
 0.14285714 0.15384615 0.16666667 0.18918919 0.19444444 0.19047619
 0.21428571 0.25       0.23809524 0.26190476 0.30952381 0.33333333
 0.35714286 0.38095238 0.4047619  0.425      0.42857143 0.45238095
 0.46153846 0.48648649 0.47619048 0.5        0.56756757 0.53846154
 0.52380952 0.54761905 0.57142857 0.55263158 0.54054054 0.58333333
 0.475      0.47368421 0.43589744 0.5952381  0.65789474 0.66666667
 0.69047619 0.64285714 0.61904762 0.69230769 0.71428571 0.77777778
 0.725      0.67567568 0.65853659 0.6097561  0.61538462 0.625
 0.69444444 0.58536585 0.63888889 0.53658537 0.59459459 0.525
 0.48717949 0.4        0.56410256 0.75       0.71794872 0.68421053
 0.74358974 0.76190476 0.73809524 0.775      0.83783784 0.73684211
 0.62162162 0.51282051 0.57894737 0.64102564 0.86486486 0.80952381
 0.78571429 0.8        0.80487805 0.81578947 0.73170732 0.60526316
 0.575      0.44444444 0.36585366 0.72972973 0.63157895 0.71052632
 0.38461538 0.3902439  0.47222222 0.43902439 0.52777778 0.48780488
 0.52631579 0.64864865 0.58974359 0.72222222 0.55       0.6
 0.68292683 0.89473684 0.83333333 0.85714286 0.92857143 0.92682927
 0.9047619  1.         0.95238095 0.97619048 0.85365854 0.94736842
 0.63414634 0.56097561 0.7027027  0.42105263 0.51351351 0.41666667
 0.35       0.78947368 0.94444444 0.78378378 0.81081081 0.65
 0.41025641 0.44736842 0.375      0.37837838 0.38888889 0.80555556
 0.7        0.76923077 0.88095238 0.76315789 0.36842105 0.28571429
 0.36111111 0.34146341 0.675      0.28947368 0.275      0.27777778
 0.24390244 0.87179487 0.86842105 0.45       0.45945946 0.46341463
 0.84210526 0.97222222 0.51219512 0.43243243 0.3        0.29268293
 0.61111111 0.40540541 0.31707317 0.26829268 0.19512195 0.39473684
 0.41463415 0.25641026 0.34210526 0.30769231 0.35897436 0.55555556
 0.75675676 0.70731707 0.27027027 0.26315789 0.225      0.28205128
 0.325      0.86111111 0.75609756 0.7804878  0.925      0.97368421
 0.88888889 0.91891892 0.82926829 0.825      0.89189189 0.91666667
 0.9        0.20512821 0.24324324 0.35135135 0.31578947 0.2972973
 0.30555556 0.07142857 0.0625     0.125      0.13333333 0.1875
 0.3125     0.4375     0.5625     0.8125     0.86666667 0.9375
 0.875      0.93333333 0.6875     0.73333333 0.53333333 0.46666667
 0.26666667 0.06666667 0.11111111 0.22222222 0.05555556 0.05882353
 0.29411765 0.35294118 0.58823529 0.64705882 0.52941176 0.88235294
 0.82352941 0.70588235 0.76470588 0.94117647 0.41176471 0.47058824
 0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091 0.2        0.1
 0.11764706 0.17647059 0.23529412 0.07692308 0.23076923 0.84615385
 0.92307692 0.05263158 0.07894737 0.13157895 0.15789474 0.21052632
 0.23684211 0.92105263 0.93939394 0.91428571 0.97058824 0.85294118
 0.91176471 0.78787879 0.74285714 0.94594595 0.79411765 0.94285714
 0.82857143 0.67647059 0.73529412 0.75757576 0.96969697 0.87878788
 0.88571429 0.61764706 0.97297297 0.68571429 0.84848485 0.55882353
 0.54285714 0.77142857 0.51428571 0.42424242 0.39393939 0.34285714
 0.57575758 0.48484848 0.6969697  0.65714286 0.45714286 0.60606061
 0.97142857 0.38235294 0.48571429 0.44117647 0.51515152 0.62857143
 0.02857143 0.05714286 0.08571429 0.17142857 0.22857143 0.25714286
 0.40625    0.37142857 0.53125    0.96666667 0.65625    0.63333333
 0.76666667 0.96875    0.96774194 0.90322581 0.84375    0.87096774
 0.70967742 0.56666667 0.5483871  0.80645161 0.46875    0.41935484
 0.31428571 0.36666667 0.59375    0.78125    0.71875    0.90625
 0.74193548 0.51612903 0.67741935 0.83870968 0.48387097 0.58064516
 0.34375    0.38709677 0.93548387 0.77419355 0.61290323 0.64516129
 0.03333333 0.11428571 0.4516129  0.35483871 0.43333333 0.32258065
 0.28125    0.02631579 0.08108108 0.08333333 0.10526316 0.15151515
 0.18421053 0.32432432 0.3030303  0.03571429 0.10714286 0.17857143
 0.20833333 0.24       0.2962963  0.32142857 0.39285714 0.46428571
 0.53571429 0.60714286 0.56       0.67857143 0.72       0.76
 0.82142857 0.96428571 0.89285714 0.88461538 0.96       0.96153846
 0.96296296 0.81481481 0.85185185 0.92       0.95833333 0.74074074
 0.92592593 0.79166667 0.88       0.64       0.68       0.70833333
 0.73076923 0.80769231 0.65384615 0.84       0.7037037  0.62962963
 0.57692308 0.37037037 0.45833333 0.44       0.54166667 0.48148148
 0.48       0.52       0.59259259 0.51851852 0.40740741 0.42307692
 0.25925926 0.36       0.14814815 0.16       0.34615385 0.01724138
 0.03448276 0.05172414 0.06896552 0.0862069  0.10344828 0.14
 0.1372549  0.12068966 0.14035088 0.13793103 0.15686275 0.1509434
 0.15517241 0.17241379 0.21568627 0.18965517 0.19642857 0.19298246
 0.22       0.22413793 0.24137931 0.25862069 0.27586207 0.29310345
 0.31481481 0.31034483 0.32758621 0.34482759 0.33962264 0.36538462
 0.36206897 0.37931034 0.38596491 0.39655172 0.41071429 0.46551724
 0.44827586 0.48275862 0.48214286 0.4137931  0.43103448 0.51923077
 0.41818182 0.45098039 0.43859649 0.49056604 0.50909091 0.56862745
 0.55769231 0.51724138 0.53448276 0.55172414 0.62264151 0.56896552
 0.62745098 0.60344828 0.62068966 0.63793103 0.65517241 0.67241379
 0.61403509 0.5862069  0.56140351 0.56603774 0.54385965 0.51785714
 0.45614035 0.49019608 0.60377358 0.7254902  0.78       0.68965517
 0.73584906 0.70909091 0.68518519 0.60784314 0.52830189 0.58181818
 0.58490566 0.59649123 0.58928571 0.54       0.78846154 0.72413793
 0.74137931 0.75862069 0.77586207 0.79310345 0.80701754 0.7962963
 0.79245283 0.76785714 0.70689655 0.69090909 0.69642857 0.64150943
 0.71929825 0.75438596 0.67307692 0.66       0.62       0.55357143
 0.68627451 0.56363636 0.49122807 0.44230769 0.47169811 0.50943396
 0.38       0.37254902 0.35185185 0.32727273 0.38181818 0.35087719
 0.66037736 0.64814815 0.44642857 0.37735849 0.33928571 0.35849057
 0.34545455 0.26785714 0.28846154 0.26923077 0.43636364 0.46
 0.45283019 0.42592593 0.50980392 0.58       0.29824561 0.32
 0.47272727 0.30909091 0.41509434 0.32692308 0.40350877 0.20689655
 0.39622642 0.42       0.43396226 0.32075472 0.43137255 0.29090909
 0.54901961 0.57407407 0.39215686 0.34       0.28       0.2745098
 0.48076923 0.40384615 0.59615385 0.21818182 0.24528302 0.22807018
 0.26415094 0.28070175 0.24074074 0.26       0.69811321 0.54716981
 0.65454545 0.63461538 0.49090909 0.53703704 0.52727273 0.30357143
 0.46296296 0.71698113 0.64912281 0.30188679 0.31372549 0.67924528
 0.71153846 0.50877193 0.74       0.21153846 0.17307692 0.20754717
 0.25454545 0.18867925 0.18       0.2037037  0.23214286 0.19230769
 0.18518519 0.29166667 0.47826087 0.60869565 0.69565217 0.65217391
 0.77272727 0.86363636 0.95454545 0.82608696 0.95652174 0.91304348
 0.7826087  0.86956522 0.68181818 0.73913043 0.43478261 0.52173913
 0.40909091 0.59090909 0.56521739 0.26086957 0.31818182 0.34782609
 0.95       0.85       0.05       0.15       0.03125    0.09375
 0.21875    0.82758621 0.86206897 0.93103448 0.96551724 0.89655172
 0.15625    0.19354839 0.29032258 0.25806452 0.23333333]

In [251]:
# Convert the datetime column to datetime format
bd["datetime"] = pd.to_datetime(bd["datetime"])

In [252]:
# Staffed beds cannot exceed total beds
bd[bd["staffed_beds"] > bd["total_beds"]]

Empty DataFrame
Columns: [datetime, hospital_id, ward, bed_type, total_beds, staffed_beds, occupied_beds, closed_beds, occupancy_rate]
Index: []

In [253]:
# Closed beds cannot be negative
bd[bd["closed_beds"] < 0]

Empty DataFrame
Columns: [datetime, hospital_id, ward, bed_type, total_beds, staffed_beds, occupied_beds, closed_beds, occupancy_rate]
Index: []

In [254]:
# Occupancy rate should be between 0 and 1
bd[(bd["occupancy_rate"] < 0) | (bd["occupancy_rate"] > 1)]

Empty DataFrame
Columns: [datetime, hospital_id, ward, bed_type, total_beds, staffed_beds, occupied_beds, closed_beds, occupancy_rate]
Index: []

##### Outpatient Arrivals Dataset Overview

In [255]:
print("="*50)
print("Outpatient Arrivals Dataset Overview")
print("="*50)

print("\nFirst 5 Rows:")
print(oa.head())

print(f"Rows: {oa.shape[0]}")
print(f"Columns: {oa.shape[1]}")
print(f"Shape: {oa.shape}")

print("\nColumn Names:")
print(oa.columns.tolist())

print("\nData Types:")
print(oa.dtypes)

print("\nMissing Values:")
print(oa.isnull().sum())

print("\nDuplicate Rows:")
print(oa.duplicated().sum())

print("\nUnique Values:")
print(oa.nunique())

for col in oa.columns:
    print(f"\n{col}")
    print(oa[col].unique())

==================================================
Outpatient Arrivals Dataset Overview
==================================================

First 5 Rows:
  hospital_id   arrival_id     arrival_datetime triage_category  \
0  HHN-LON-01  ARR00000001  2024-01-01 06:50:00        Standard
1  HHN-LON-01  ARR00000002  2024-01-01 22:06:00        Standard
2  HHN-LON-01  ARR00000003  2024-01-01 18:43:00        Standard
3  HHN-LON-01  ARR00000004  2024-01-01 18:08:00        Standard
4  HHN-LON-01  ARR00000005  2024-01-01 07:44:00      Non-Urgent

     arrival_mode                 outcome  time_to_admission  bed_requested
0       Ambulance         Discharged Home                NaN          False
1  Self-Presented         Discharged Home                NaN          False
2     Gp Referral         Discharged Home                NaN          False
3     Gp Referral  Referred to Outpatient                NaN          False
4  Self-Presented         Discharged Home                NaN          False
Rows: 361975
Columns: 8
Shape: (361975, 8)

Column Names:
['hospital_id', 'arrival_id', 'arrival_datetime', 'triage_category', 'arrival_mode', 'outcome', 'time_to_admission', 'bed_requested']

Data Types:
hospital_id           object
arrival_id            object
arrival_datetime      object
triage_category       object
arrival_mode          object
outcome               object
time_to_admission    float64
bed_requested           bool
dtype: object

Missing Values:
hospital_id               0
arrival_id                0
arrival_datetime          0
triage_category           0
arrival_mode              0
outcome                   0
time_to_admission    255459
bed_requested             0
dtype: int64

Duplicate Rows:
0

Unique Values:
hospital_id               5
arrival_id           361975
arrival_datetime     292628
triage_category           5
arrival_mode              4
outcome                   5
time_to_admission       556
bed_requested             2
dtype: int64

hospital_id
['HHN-LON-01' 'HHN-LON-02' 'HHN-MAN-01' 'HHN-BIR-01' 'HHN-EDI-01']

arrival_id
['ARR00000001' 'ARR00000002' 'ARR00000003' ... 'ARR00361973' 'ARR00361974'
 'ARR00361975']

arrival_datetime
['2024-01-01 06:50:00' '2024-01-01 22:06:00' '2024-01-01 18:43:00' ...
 '2025-12-31 07:43:00' '2025-12-31 21:37:00' '2025-12-31 16:03:00']

triage_category
['Standard' 'Non-Urgent' 'Urgent' 'Emergency' 'Resuscitation']

arrival_mode
['Ambulance' 'Self-Presented' 'Gp Referral' 'Inter-Hospital Transfer']

outcome
['Discharged Home' 'Referred to Outpatient' 'Admitted' 'Transferred'
 'Left Without Being Seen']

time_to_admission
[ nan  73. 123. 441.  75. 165. 196. 252. 340.  85. 180. 144.  55.  10.
 166. 118. 224.  45. 158. 214.  41.  64. 119.  97.  99. 129. 108.  56.
 269. 433. 380.  94. 198.  66. 239. 112. 217. 149.  49. 238. 173. 132.
 273. 222. 254.  21. 194. 246.  98.  82.  32. 162. 244.  76. 209. 157.
  61. 206. 134. 128. 301. 139. 169. 218.  91.  22.  13. 259. 210. 339.
 303. 245. 240.  53.  29. 152. 279.  86. 192. 199. 100. 114.  16. 154.
  79. 186. 177. 104. 213. 131.  93. 102. 237. 178.  72.  54. 226. 306.
 220.  95. 111. 256.  84.  81. 146. 270. 187. 126.  38. 241. 223. 375.
 171. 159. 191. 262. 143.  68. 167.  42. 227. 130. 127.  92. 160.  58.
 150. 331. 264. 370. 309. 135. 110. 473. 103. 201. 124. 347. 243. 369.
 286. 190.  43. 296.  37.  87. 257.  15. 287.  83. 140. 133. 183. 205.
 200. 170. 376. 250. 117. 174. 113.  47. 107.  50.  25. 266. 437. 268.
 101. 155. 163. 188. 164. 216. 116. 219. 221. 185.  77. 105. 189. 204.
  96. 161. 255. 181. 470.  35. 195. 120. 276.  88. 361. 291.  31. 225.
  74. 341. 293. 551. 386.  89. 148. 330. 176. 233. 277. 235. 168. 326.
 172. 156. 249. 136. 258. 280. 215. 377. 298.  17.  70. 151. 318. 247.
 311.  65. 418. 350.  23.  59.  62. 274. 315.  51.  71. 193. 324. 459.
 122. 271. 283.  26. 343. 428. 407.  78.  27.  90. 321. 312. 336. 308.
  28. 232. 142. 371. 275. 138.  20. 261. 248. 145. 109. 208. 125. 106.
  57.  48. 229. 429. 236. 141.  39. 359.  18. 278. 202. 179. 263. 297.
 137. 182. 197. 319. 153. 305. 260. 147. 333. 393. 322. 203. 451. 385.
 272. 212. 329.  60. 304. 282.  14.  33. 310. 313. 328. 300.  34. 435.
 334. 115. 493. 207. 294.  46. 211. 184. 302.  52. 265. 299.  30. 355.
 290.  40. 121. 396.  69. 381. 404. 357. 352. 234. 549. 325. 230. 338.
 406. 510.  67. 281. 383. 317. 465. 351. 267. 413. 345. 354.  80. 349.
 382. 374. 251.  36. 401. 475. 521. 253. 228. 414. 242. 175. 366. 332.
 368. 398.  44. 364. 231. 409. 388.  63. 307. 320. 348. 316. 389. 412.
 403. 431. 323. 378. 289. 285. 342. 477.  11.  24.  19. 399. 295. 436.
 387. 335. 419. 390. 395. 472. 346. 353. 438. 337. 379. 288.  12. 292.
 284. 384. 362. 446. 373. 408. 415. 425. 417. 500. 360. 394. 434. 344.
 365. 356. 424. 550. 314. 449. 505. 363. 367. 442. 452. 482. 391. 421.
 444. 358. 448. 327. 397. 511. 410. 411. 497. 372. 463. 405. 402. 422.
 455. 426. 464. 483. 602. 392. 545. 430. 486. 420. 450. 494. 479. 400.
 454. 458. 566. 432. 530. 416. 460. 531. 526. 423. 462. 548. 457. 524.
 490. 471. 443. 474. 564. 579. 498. 609. 469. 453. 447. 427. 440. 487.
 537. 525. 467. 461. 533. 590. 456. 502. 542. 532. 574. 515. 445. 520.
 476. 516. 587. 615. 507. 620. 480. 501. 541. 468. 567. 504. 581. 528.
 488. 536. 517. 557. 554. 485. 568. 535. 491. 492. 563. 544. 523. 499.
 506. 484. 513. 588. 529. 509. 478. 466. 578. 481. 439. 489. 636. 512.
 606. 570. 514. 553. 547. 543. 577. 546. 495. 496. 600.]

bed_requested
[False  True]

In [256]:
# Convert the arrival datetime column to datetime format
oa["arrival_datetime"] = pd.to_datetime(oa["arrival_datetime"])

In [257]:
# Check for missing values in the time_to_admission column
oa[oa["time_to_admission"].isna()]

,hospital_id,arrival_id,arrival_datetime,triage_category,arrival_mode,outcome,time_to_admission,bed_requested
0,HHN-LON-01,ARR00000001,2024-01-01 06:50:00,Standard,Ambulance,Discharged Home,NaN,False
1,HHN-LON-01,ARR00000002,2024-01-01 22:06:00,Standard,Self-Presented,Discharged Home,NaN,False
2,HHN-LON-01,ARR00000003,2024-01-01 18:43:00,Standard,Gp Referral,Discharged Home,NaN,False
3,HHN-LON-01,ARR00000004,2024-01-01 18:08:00,Standard,Gp Referral,Referred to Outpatient,NaN,False
4,HHN-LON-01,ARR00000005,2024-01-01 07:44:00,Non-Urgent,Self-Presented,Discharged Home,NaN,False
...,...,...,...,...,...,...,...,...
361969,HHN-EDI-01,ARR00361970,2025-12-31 07:43:00,Standard,Ambulance,Discharged Home,NaN,False
361970,HHN-EDI-01,ARR00361971,2025-12-31 21:37:00,Standard,Ambulance,Discharged Home,NaN,False
361971,HHN-EDI-01,ARR00361972,2025-12-31 15:00:00,Standard,Self-Presented,Referred to Outpatient,NaN,False
361972,HHN-EDI-01,ARR00361973,2025-12-31 10:46:00,Standard,Gp Referral,Discharged Home,NaN,False
361974,HHN-EDI-01,ARR00361975,2025-12-31 19:07:00,Standard,Self-Presented,Referred to Outpatient,NaN,False

In [258]:
# Fill missing values in the time_to_admission column with 0
oa["time_to_admission"] = oa["time_to_admission"].fillna(0)
oa["time_to_admission"].isna().sum()

np.int64(0)

##### Elective Surgery Dataset Overview

In [259]:
print("="*50)
print("Elective Surgery Dataset Overview")
print("="*50)

print("\nFirst 5 Rows:")
print(es.head())

print(f"Rows: {es.shape[0]}")
print(f"Columns: {es.shape[1]}")
print(f"Shape: {es.shape}")

print("\nColumn Names:")
print(es.columns.tolist())

print("\nData Types:")
print(es.dtypes)

print("\nMissing Values:")
print(es.isnull().sum())

print("\nDuplicate Rows:")
print(es.duplicated().sum())

print("\nUnique Values:")
print(es.nunique())

for col in es.columns:
    print(f"\n{col}")
    print(es[col].unique())

==================================================
Elective Surgery Dataset Overview
==================================================

First 5 Rows:
  hospital_id   surgery_id surgery_date     specialty   procedure_group  \
0  HHN-LON-01  SUR00000001   2024-01-02   Diagnostics  CT-Guided Biopsy
1  HHN-LON-01  SUR00000002   2024-01-02  Orthopaedics     Spinal Fusion
2  HHN-LON-01  SUR00000003   2024-01-03  Orthopaedics     Spinal Fusion
3  HHN-LON-01  SUR00000004   2024-01-03   Diagnostics       Stress Test
4  HHN-LON-01  SUR00000005   2024-01-03   Diagnostics      MRI Day Case

   expected_los_days bed_type_required surgery_status cancellation_reason
0                0.2          Standard      Completed                 NaN
1                2.8          Standard      Completed                 NaN
2                3.2          Standard      Completed                 NaN
3                0.2          Standard      Completed                 NaN
4                0.2          Standard      Completed                 NaN
Rows: 25355
Columns: 9
Shape: (25355, 9)

Column Names:
['hospital_id', 'surgery_id', 'surgery_date', 'specialty', 'procedure_group', 'expected_los_days', 'bed_type_required', 'surgery_status', 'cancellation_reason']

Data Types:
hospital_id             object
surgery_id              object
surgery_date            object
specialty               object
procedure_group         object
expected_los_days      float64
bed_type_required       object
surgery_status          object
cancellation_reason     object
dtype: object

Missing Values:
hospital_id                0
surgery_id                 0
surgery_date               0
specialty                  0
procedure_group            0
expected_los_days        507
bed_type_required          0
surgery_status             0
cancellation_reason    23365
dtype: int64

Duplicate Rows:
0

Unique Values:
hospital_id                5
surgery_id             25355
surgery_date             507
specialty                  4
procedure_group           17
expected_los_days        129
bed_type_required          2
surgery_status             2
cancellation_reason        5
dtype: int64

hospital_id
['HHN-LON-01' 'HHN-LON-02' 'HHN-MAN-01' 'HHN-BIR-01' 'HHN-EDI-01']

surgery_id
['SUR00000001' 'SUR00000002' 'SUR00000003' ... 'SUR00025353' 'SUR00025354'
 'SUR00025355']

surgery_date
['2024-01-02' '2024-01-03' '2024-01-04' '2024-01-05' '2024-01-08'
 '2024-01-09' '2024-01-10' '2024-01-11' '2024-01-12' '2024-01-15'
 '2024-01-16' '2024-01-17' '2024-01-18' '2024-01-19' '2024-01-22'
 '2024-01-23' '2024-01-24' '2024-01-25' '2024-01-26' '2024-01-29'
 '2024-01-30' '2024-01-31' '2024-02-01' '2024-02-02' '2024-02-05'
 '2024-02-06' '2024-02-07' '2024-02-08' '2024-02-09' '2024-02-12'
 '2024-02-13' '2024-02-14' '2024-02-15' '2024-02-16' '2024-02-19'
 '2024-02-20' '2024-02-21' '2024-02-22' '2024-02-23' '2024-02-26'
 '2024-02-27' '2024-02-28' '2024-02-29' '2024-03-01' '2024-03-04'
 '2024-03-05' '2024-03-06' '2024-03-07' '2024-03-08' '2024-03-11'
 '2024-03-12' '2024-03-13' '2024-03-14' '2024-03-15' '2024-03-18'
 '2024-03-19' '2024-03-20' '2024-03-21' '2024-03-22' '2024-03-25'
 '2024-03-26' '2024-03-27' '2024-03-28' '2024-04-02' '2024-04-03'
 '2024-04-04' '2024-04-05' '2024-04-08' '2024-04-09' '2024-04-10'
 '2024-04-11' '2024-04-12' '2024-04-15' '2024-04-16' '2024-04-17'
 '2024-04-18' '2024-04-19' '2024-04-22' '2024-04-23' '2024-04-24'
 '2024-04-25' '2024-04-26' '2024-04-29' '2024-04-30' '2024-05-01'
 '2024-05-02' '2024-05-03' '2024-05-07' '2024-05-08' '2024-05-09'
 '2024-05-10' '2024-05-13' '2024-05-14' '2024-05-15' '2024-05-16'
 '2024-05-17' '2024-05-20' '2024-05-21' '2024-05-22' '2024-05-23'
 '2024-05-24' '2024-05-28' '2024-05-29' '2024-05-30' '2024-05-31'
 '2024-06-03' '2024-06-04' '2024-06-05' '2024-06-06' '2024-06-07'
 '2024-06-10' '2024-06-11' '2024-06-12' '2024-06-13' '2024-06-14'
 '2024-06-17' '2024-06-18' '2024-06-19' '2024-06-20' '2024-06-21'
 '2024-06-24' '2024-06-25' '2024-06-26' '2024-06-27' '2024-06-28'
 '2024-07-01' '2024-07-02' '2024-07-03' '2024-07-04' '2024-07-05'
 '2024-07-08' '2024-07-09' '2024-07-10' '2024-07-11' '2024-07-12'
 '2024-07-15' '2024-07-16' '2024-07-17' '2024-07-18' '2024-07-19'
 '2024-07-22' '2024-07-23' '2024-07-24' '2024-07-25' '2024-07-26'
 '2024-07-29' '2024-07-30' '2024-07-31' '2024-08-01' '2024-08-02'
 '2024-08-05' '2024-08-06' '2024-08-07' '2024-08-08' '2024-08-09'
 '2024-08-12' '2024-08-13' '2024-08-14' '2024-08-15' '2024-08-16'
 '2024-08-19' '2024-08-20' '2024-08-21' '2024-08-22' '2024-08-23'
 '2024-08-27' '2024-08-28' '2024-08-29' '2024-08-30' '2024-09-02'
 '2024-09-03' '2024-09-04' '2024-09-05' '2024-09-06' '2024-09-09'
 '2024-09-10' '2024-09-11' '2024-09-12' '2024-09-13' '2024-09-16'
 '2024-09-17' '2024-09-18' '2024-09-19' '2024-09-20' '2024-09-23'
 '2024-09-24' '2024-09-25' '2024-09-26' '2024-09-27' '2024-09-30'
 '2024-10-01' '2024-10-02' '2024-10-03' '2024-10-04' '2024-10-07'
 '2024-10-08' '2024-10-09' '2024-10-10' '2024-10-11' '2024-10-14'
 '2024-10-15' '2024-10-16' '2024-10-17' '2024-10-18' '2024-10-21'
 '2024-10-22' '2024-10-23' '2024-10-24' '2024-10-25' '2024-10-28'
 '2024-10-29' '2024-10-30' '2024-10-31' '2024-11-01' '2024-11-04'
 '2024-11-05' '2024-11-06' '2024-11-07' '2024-11-08' '2024-11-11'
 '2024-11-12' '2024-11-13' '2024-11-14' '2024-11-15' '2024-11-18'
 '2024-11-19' '2024-11-20' '2024-11-21' '2024-11-22' '2024-11-25'
 '2024-11-26' '2024-11-27' '2024-11-28' '2024-11-29' '2024-12-02'
 '2024-12-03' '2024-12-04' '2024-12-05' '2024-12-06' '2024-12-09'
 '2024-12-10' '2024-12-11' '2024-12-12' '2024-12-13' '2024-12-16'
 '2024-12-17' '2024-12-18' '2024-12-19' '2024-12-20' '2024-12-23'
 '2024-12-24' '2024-12-27' '2024-12-30' '2024-12-31' '2025-01-02'
 '2025-01-03' '2025-01-06' '2025-01-07' '2025-01-08' '2025-01-09'
 '2025-01-10' '2025-01-13' '2025-01-14' '2025-01-15' '2025-01-16'
 '2025-01-17' '2025-01-20' '2025-01-21' '2025-01-22' '2025-01-23'
 '2025-01-24' '2025-01-27' '2025-01-28' '2025-01-29' '2025-01-30'
 '2025-01-31' '2025-02-03' '2025-02-04' '2025-02-05' '2025-02-06'
 '2025-02-07' '2025-02-10' '2025-02-11' '2025-02-12' '2025-02-13'
 '2025-02-14' '2025-02-17' '2025-02-18' '2025-02-19' '2025-02-20'
 '2025-02-21' '2025-02-24' '2025-02-25' '2025-02-26' '2025-02-27'
 '2025-02-28' '2025-03-03' '2025-03-04' '2025-03-05' '2025-03-06'
 '2025-03-07' '2025-03-10' '2025-03-11' '2025-03-12' '2025-03-13'
 '2025-03-14' '2025-03-17' '2025-03-18' '2025-03-19' '2025-03-20'
 '2025-03-21' '2025-03-24' '2025-03-25' '2025-03-26' '2025-03-27'
 '2025-03-28' '2025-03-31' '2025-04-01' '2025-04-02' '2025-04-03'
 '2025-04-04' '2025-04-07' '2025-04-08' '2025-04-09' '2025-04-10'
 '2025-04-11' '2025-04-14' '2025-04-15' '2025-04-16' '2025-04-17'
 '2025-04-22' '2025-04-23' '2025-04-24' '2025-04-25' '2025-04-28'
 '2025-04-29' '2025-04-30' '2025-05-01' '2025-05-02' '2025-05-06'
 '2025-05-07' '2025-05-08' '2025-05-09' '2025-05-12' '2025-05-13'
 '2025-05-14' '2025-05-15' '2025-05-16' '2025-05-19' '2025-05-20'
 '2025-05-21' '2025-05-22' '2025-05-23' '2025-05-27' '2025-05-28'
 '2025-05-29' '2025-05-30' '2025-06-02' '2025-06-03' '2025-06-04'
 '2025-06-05' '2025-06-06' '2025-06-09' '2025-06-10' '2025-06-11'
 '2025-06-12' '2025-06-13' '2025-06-16' '2025-06-17' '2025-06-18'
 '2025-06-19' '2025-06-20' '2025-06-23' '2025-06-24' '2025-06-25'
 '2025-06-26' '2025-06-27' '2025-06-30' '2025-07-01' '2025-07-02'
 '2025-07-03' '2025-07-04' '2025-07-07' '2025-07-08' '2025-07-09'
 '2025-07-10' '2025-07-11' '2025-07-14' '2025-07-15' '2025-07-16'
 '2025-07-17' '2025-07-18' '2025-07-21' '2025-07-22' '2025-07-23'
 '2025-07-24' '2025-07-25' '2025-07-28' '2025-07-29' '2025-07-30'
 '2025-07-31' '2025-08-01' '2025-08-04' '2025-08-05' '2025-08-06'
 '2025-08-07' '2025-08-08' '2025-08-11' '2025-08-12' '2025-08-13'
 '2025-08-14' '2025-08-15' '2025-08-18' '2025-08-19' '2025-08-20'
 '2025-08-21' '2025-08-22' '2025-08-26' '2025-08-27' '2025-08-28'
 '2025-08-29' '2025-09-01' '2025-09-02' '2025-09-03' '2025-09-04'
 '2025-09-05' '2025-09-08' '2025-09-09' '2025-09-10' '2025-09-11'
 '2025-09-12' '2025-09-15' '2025-09-16' '2025-09-17' '2025-09-18'
 '2025-09-19' '2025-09-22' '2025-09-23' '2025-09-24' '2025-09-25'
 '2025-09-26' '2025-09-29' '2025-09-30' '2025-10-01' '2025-10-02'
 '2025-10-03' '2025-10-06' '2025-10-07' '2025-10-08' '2025-10-09'
 '2025-10-10' '2025-10-13' '2025-10-14' '2025-10-15' '2025-10-16'
 '2025-10-17' '2025-10-20' '2025-10-21' '2025-10-22' '2025-10-23'
 '2025-10-24' '2025-10-27' '2025-10-28' '2025-10-29' '2025-10-30'
 '2025-10-31' '2025-11-03' '2025-11-04' '2025-11-05' '2025-11-06'
 '2025-11-07' '2025-11-10' '2025-11-11' '2025-11-12' '2025-11-13'
 '2025-11-14' '2025-11-17' '2025-11-18' '2025-11-19' '2025-11-20'
 '2025-11-21' '2025-11-24' '2025-11-25' '2025-11-26' '2025-11-27'
 '2025-11-28' '2025-12-01' '2025-12-02' '2025-12-03' '2025-12-04'
 '2025-12-05' '2025-12-08' '2025-12-09' '2025-12-10' '2025-12-11'
 '2025-12-12' '2025-12-15' '2025-12-16' '2025-12-17' '2025-12-18'
 '2025-12-19' '2025-12-22' '2025-12-23' '2025-12-24' '2025-12-29'
 '2025-12-30' '2025-12-31']

specialty
['Diagnostics' 'Orthopaedics' 'Cardiology' 'Oncology']

procedure_group
['CT-Guided Biopsy' 'Spinal Fusion' 'Stress Test' 'MRI Day Case'
 'Hip Replacement' 'Bypass Graft' 'Knee Replacement'
 'Cardiac Catheterisation' 'Biopsy Procedure' 'Radiotherapy Prep'
 'Fracture Repair' 'Chemotherapy Admission' 'Angioplasty' 'Endoscopy'
 'Tumour Resection' 'Arthroscopy' 'Pacemaker Insertion']

expected_los_days
[ 0.2  2.8  3.2  2.   2.9  4.4  4.   2.1  3.   3.9  1.7  1.2  4.7  3.1
  5.7  3.3  4.1  2.5  3.5  4.5  0.3  5.5  5.   2.2  5.1  3.7  4.2  3.8
  3.4  5.8  2.7  3.6  2.3  7.5  6.2  2.4  5.2  2.6  nan  6.3  6.7  1.9
  8.7  8.5  1.5  7.3  5.4  4.6  6.1  1.4  4.8 14.7  4.3  7.4  5.3  5.6
 12.5 11.2  1.8  1.3  7.   1.1  1.6  5.9  9.3  8.2  6.4  7.6  6.   6.6
  8.1  4.9  7.2  7.1  1.   8.6 10.9  9.9 11.1  6.5  6.9  8.8  7.7  9.2
  9.1  8.4 10.5  6.8  8.3  7.9  8.9 10.  13.8  7.8 10.4  9.  11.4 10.8
  9.6  8.   9.5 10.2  9.7 10.6 13.3 10.3 11.8 11.  10.7 12.2 15.  11.5
 10.1 12.1 12.  12.4 13.1 13.  11.3  9.8 17.2 12.7  0.9 22.5  0.4  9.4
 14.3  0.7 12.8  0.8]

bed_type_required
['Standard' 'ICU Step-down']

surgery_status
['Completed' 'Cancelled']

cancellation_reason
[nan 'Patient Request' 'Theatre Unavailable' 'Staffing Shortage'
 'Clinical Reason' 'Bed Unavailable']

In [260]:
# Check for missing values in the expected_los_days column
es[es["expected_los_days"].isna()]

,hospital_id,surgery_id,surgery_date,specialty,procedure_group,expected_los_days,bed_type_required,surgery_status,cancellation_reason
93,HHN-LON-01,SUR00000094,2024-01-15,Orthopaedics,Fracture Repair,NaN,Standard,Completed,NaN
199,HHN-LON-01,SUR00000200,2024-01-26,Orthopaedics,Spinal Fusion,NaN,Standard,Completed,NaN
231,HHN-LON-01,SUR00000232,2024-01-31,Oncology,Radiotherapy Prep,NaN,Standard,Completed,NaN
375,HHN-LON-01,SUR00000376,2024-02-15,Oncology,Tumour Resection,NaN,Standard,Completed,NaN
449,HHN-LON-01,SUR00000450,2024-02-22,Cardiology,Cardiac Catheterisation,NaN,Standard,Completed,NaN
...,...,...,...,...,...,...,...,...,...
25036,HHN-EDI-01,SUR00025037,2025-09-25,Orthopaedics,Arthroscopy,NaN,Standard,Completed,NaN
25109,HHN-EDI-01,SUR00025110,2025-10-14,Cardiology,Pacemaker Insertion,NaN,Standard,Completed,NaN
25171,HHN-EDI-01,SUR00025172,2025-11-03,Orthopaedics,Arthroscopy,NaN,Standard,Completed,NaN
25184,HHN-EDI-01,SUR00025185,2025-11-06,Oncology,Tumour Resection,NaN,Standard,Completed,NaN
25329,HHN-EDI-01,SUR00025330,2025-12-15,Oncology,Biopsy Procedure,NaN,Standard,Completed,NaN

In [261]:
# Calculate the median for each procedure
procedure_median = es.groupby("procedure_group")["expected_los_days"].median()

# Fill missing values
es["expected_los_days"] = es["expected_los_days"].fillna(es["procedure_group"].map(procedure_median))

# check for missing values in the expected_los_days column after filling
es[es["expected_los_days"].isna()]

Empty DataFrame
Columns: [hospital_id, surgery_id, surgery_date, specialty, procedure_group, expected_los_days, bed_type_required, surgery_status, cancellation_reason]
Index: []

In [262]:
# Check for missing values in the cancellation_reason column
es[es["cancellation_reason"].isna()]

,hospital_id,surgery_id,surgery_date,specialty,procedure_group,expected_los_days,bed_type_required,surgery_status,cancellation_reason
0,HHN-LON-01,SUR00000001,2024-01-02,Diagnostics,CT-Guided Biopsy,0.2,Standard,Completed,NaN
1,HHN-LON-01,SUR00000002,2024-01-02,Orthopaedics,Spinal Fusion,2.8,Standard,Completed,NaN
2,HHN-LON-01,SUR00000003,2024-01-03,Orthopaedics,Spinal Fusion,3.2,Standard,Completed,NaN
3,HHN-LON-01,SUR00000004,2024-01-03,Diagnostics,Stress Test,0.2,Standard,Completed,NaN
4,HHN-LON-01,SUR00000005,2024-01-03,Diagnostics,MRI Day Case,0.2,Standard,Completed,NaN
...,...,...,...,...,...,...,...,...,...
25349,HHN-EDI-01,SUR00025350,2025-12-29,Orthopaedics,Fracture Repair,3.1,Standard,Completed,NaN
25350,HHN-EDI-01,SUR00025351,2025-12-29,Diagnostics,MRI Day Case,0.2,Standard,Completed,NaN
25351,HHN-EDI-01,SUR00025352,2025-12-29,Diagnostics,Stress Test,0.2,Standard,Completed,NaN
25352,HHN-EDI-01,SUR00025353,2025-12-30,Oncology,Chemotherapy Admission,4.1,Standard,Completed,NaN
25354,HHN-EDI-01,SUR00025355,2025-12-31,Oncology,Tumour Resection,2.6,Standard,Completed,NaN

In [263]:
# Fill missing values in the time_to_admission column with 0
es["cancellation_reason"] = es["cancellation_reason"].fillna("Completed Surgery")
es["cancellation_reason"].isna().sum()

np.int64(0)

In [264]:
# Convert the date column to datetime format
es["surgery_date"] = pd.to_datetime(es["surgery_date"])

##### Hospital Reference Dataset Overview

In [265]:
print("="*50)
print("Hospital Reference Dataset Overview")
print("="*50)

print("\nFirst 5 Rows:")
print(hr.head())

print(f"Rows: {hr.shape[0]}")
print(f"Columns: {hr.shape[1]}")
print(f"Shape: {hr.shape}")

print("\nColumn Names:")
print(hr.columns.tolist())

print("\nData Types:")
print(hr.dtypes)

print("\nMissing Values:")
print(hr.isnull().sum())

print("\nDuplicate Rows:")
print(hr.duplicated().sum())

print("\nUnique Values:")
print(hr.nunique())

for col in hr.columns:
    print(f"\n{col}")
    print(hr[col].unique())

==================================================
Hospital Reference Dataset Overview
==================================================

First 5 Rows:
  hospital_id           hospital_name        city      tier  \
0  HHN-LON-01  Horizon London Central      London  Flagship
1  HHN-LON-02       Horizon Riverside      London     Large
2  HHN-MAN-01      Horizon Manchester  Manchester     Large
3  HHN-BIR-01      Horizon Birmingham  Birmingham    Medium
4  HHN-EDI-01       Horizon Edinburgh   Edinburgh    Medium

  specialty_emphasis  total_bed_capacity
0            General                 224
1           Oncology                 152
2       Orthopaedics                 164
3         Cardiology                 126
4            General                  94
Rows: 5
Columns: 6
Shape: (5, 6)

Column Names:
['hospital_id', 'hospital_name', 'city', 'tier', 'specialty_emphasis', 'total_bed_capacity']

Data Types:
hospital_id           object
hospital_name         object
city                  object
tier                  object
specialty_emphasis    object
total_bed_capacity     int64
dtype: object

Missing Values:
hospital_id           0
hospital_name         0
city                  0
tier                  0
specialty_emphasis    0
total_bed_capacity    0
dtype: int64

Duplicate Rows:
0

Unique Values:
hospital_id           5
hospital_name         5
city                  4
tier                  3
specialty_emphasis    4
total_bed_capacity    5
dtype: int64

hospital_id
['HHN-LON-01' 'HHN-LON-02' 'HHN-MAN-01' 'HHN-BIR-01' 'HHN-EDI-01']

hospital_name
['Horizon London Central' 'Horizon Riverside' 'Horizon Manchester'
 'Horizon Birmingham' 'Horizon Edinburgh']

city
['London' 'Manchester' 'Birmingham' 'Edinburgh']

tier
['Flagship' 'Large' 'Medium']

specialty_emphasis
['General' 'Oncology' 'Orthopaedics' 'Cardiology']

total_bed_capacity
[224 152 164 126  94]

Staffing Resource Dataset Overview

In [266]:
print("="*50)
print("Staffing Resource Dataset Overview")
print("="*50)

print("\nFirst 5 Rows:")
print(sr.head())

print(f"Rows: {sr.shape[0]}")
print(f"Columns: {sr.shape[1]}")
print(f"Shape: {sr.shape}")

print("\nColumn Names:")
print(sr.columns.tolist())

print("\nData Types:")
print(sr.dtypes)

print("\nMissing Values:")
print(sr.isnull().sum())

print("\nDuplicate Rows:")
print(sr.duplicated().sum())

print("\nUnique Values:")
print(sr.nunique())

for col in sr.columns:
    print(f"\n{col}")
    print(sr[col].unique())

==================================================
Staffing Resource Dataset Overview
==================================================

First 5 Rows:
         date hospital_id             ward                  staff_role  \
0  2024-01-01  HHN-BIR-01  Cardiology Ward            Registered Nurse
1  2024-01-01  HHN-BIR-01  Cardiology Ward        Healthcare Assistant
2  2024-01-01  HHN-BIR-01  Cardiology Ward                      Doctor
3  2024-01-01  HHN-BIR-01  Cardiology Ward  Allied Health Professional
4  2024-01-02  HHN-BIR-01  Cardiology Ward            Registered Nurse

   planned_staff  actual_staff  safe_ratio_met
0             10            10            True
1              5             5            True
2              4             4            True
3              1             1            True
4             10             8           False
Rows: 116960
Columns: 7
Shape: (116960, 7)

Column Names:
['date', 'hospital_id', 'ward', 'staff_role', 'planned_staff', 'actual_staff', 'safe_ratio_met']

Data Types:
date              object
hospital_id       object
ward              object
staff_role        object
planned_staff      int64
actual_staff       int64
safe_ratio_met      bool
dtype: object

Missing Values:
date              0
hospital_id       0
ward              0
staff_role        0
planned_staff     0
actual_staff      0
safe_ratio_met    0
dtype: int64

Duplicate Rows:
0

Unique Values:
date              731
hospital_id         5
ward                8
staff_role          4
planned_staff      13
actual_staff       15
safe_ratio_met      2
dtype: int64

date
['2024-01-01' '2024-01-02' '2024-01-03' '2024-01-04' '2024-01-05'
 '2024-01-06' '2024-01-07' '2024-01-08' '2024-01-09' '2024-01-10'
 '2024-01-11' '2024-01-12' '2024-01-13' '2024-01-14' '2024-01-15'
 '2024-01-16' '2024-01-17' '2024-01-18' '2024-01-19' '2024-01-20'
 '2024-01-21' '2024-01-22' '2024-01-23' '2024-01-24' '2024-01-25'
 '2024-01-26' '2024-01-27' '2024-01-28' '2024-01-29' '2024-01-30'
 '2024-01-31' '2024-02-01' '2024-02-02' '2024-02-03' '2024-02-04'
 '2024-02-05' '2024-02-06' '2024-02-07' '2024-02-08' '2024-02-09'
 '2024-02-10' '2024-02-11' '2024-02-12' '2024-02-13' '2024-02-14'
 '2024-02-15' '2024-02-16' '2024-02-17' '2024-02-18' '2024-02-19'
 '2024-02-20' '2024-02-21' '2024-02-22' '2024-02-23' '2024-02-24'
 '2024-02-25' '2024-02-26' '2024-02-27' '2024-02-28' '2024-02-29'
 '2024-03-01' '2024-03-02' '2024-03-03' '2024-03-04' '2024-03-05'
 '2024-03-06' '2024-03-07' '2024-03-08' '2024-03-09' '2024-03-10'
 '2024-03-11' '2024-03-12' '2024-03-13' '2024-03-14' '2024-03-15'
 '2024-03-16' '2024-03-17' '2024-03-18' '2024-03-19' '2024-03-20'
 '2024-03-21' '2024-03-22' '2024-03-23' '2024-03-24' '2024-03-25'
 '2024-03-26' '2024-03-27' '2024-03-28' '2024-03-29' '2024-03-30'
 '2024-03-31' '2024-04-01' '2024-04-02' '2024-04-03' '2024-04-04'
 '2024-04-05' '2024-04-06' '2024-04-07' '2024-04-08' '2024-04-09'
 '2024-04-10' '2024-04-11' '2024-04-12' '2024-04-13' '2024-04-14'
 '2024-04-15' '2024-04-16' '2024-04-17' '2024-04-18' '2024-04-19'
 '2024-04-20' '2024-04-21' '2024-04-22' '2024-04-23' '2024-04-24'
 '2024-04-25' '2024-04-26' '2024-04-27' '2024-04-28' '2024-04-29'
 '2024-04-30' '2024-05-01' '2024-05-02' '2024-05-03' '2024-05-04'
 '2024-05-05' '2024-05-06' '2024-05-07' '2024-05-08' '2024-05-09'
 '2024-05-10' '2024-05-11' '2024-05-12' '2024-05-13' '2024-05-14'
 '2024-05-15' '2024-05-16' '2024-05-17' '2024-05-18' '2024-05-19'
 '2024-05-20' '2024-05-21' '2024-05-22' '2024-05-23' '2024-05-24'
 '2024-05-25' '2024-05-26' '2024-05-27' '2024-05-28' '2024-05-29'
 '2024-05-30' '2024-05-31' '2024-06-01' '2024-06-02' '2024-06-03'
 '2024-06-04' '2024-06-05' '2024-06-06' '2024-06-07' '2024-06-08'
 '2024-06-09' '2024-06-10' '2024-06-11' '2024-06-12' '2024-06-13'
 '2024-06-14' '2024-06-15' '2024-06-16' '2024-06-17' '2024-06-18'
 '2024-06-19' '2024-06-20' '2024-06-21' '2024-06-22' '2024-06-23'
 '2024-06-24' '2024-06-25' '2024-06-26' '2024-06-27' '2024-06-28'
 '2024-06-29' '2024-06-30' '2024-07-01' '2024-07-02' '2024-07-03'
 '2024-07-04' '2024-07-05' '2024-07-06' '2024-07-07' '2024-07-08'
 '2024-07-09' '2024-07-10' '2024-07-11' '2024-07-12' '2024-07-13'
 '2024-07-14' '2024-07-15' '2024-07-16' '2024-07-17' '2024-07-18'
 '2024-07-19' '2024-07-20' '2024-07-21' '2024-07-22' '2024-07-23'
 '2024-07-24' '2024-07-25' '2024-07-26' '2024-07-27' '2024-07-28'
 '2024-07-29' '2024-07-30' '2024-07-31' '2024-08-01' '2024-08-02'
 '2024-08-03' '2024-08-04' '2024-08-05' '2024-08-06' '2024-08-07'
 '2024-08-08' '2024-08-09' '2024-08-10' '2024-08-11' '2024-08-12'
 '2024-08-13' '2024-08-14' '2024-08-15' '2024-08-16' '2024-08-17'
 '2024-08-18' '2024-08-19' '2024-08-20' '2024-08-21' '2024-08-22'
 '2024-08-23' '2024-08-24' '2024-08-25' '2024-08-26' '2024-08-27'
 '2024-08-28' '2024-08-29' '2024-08-30' '2024-08-31' '2024-09-01'
 '2024-09-02' '2024-09-03' '2024-09-04' '2024-09-05' '2024-09-06'
 '2024-09-07' '2024-09-08' '2024-09-09' '2024-09-10' '2024-09-11'
 '2024-09-12' '2024-09-13' '2024-09-14' '2024-09-15' '2024-09-16'
 '2024-09-17' '2024-09-18' '2024-09-19' '2024-09-20' '2024-09-21'
 '2024-09-22' '2024-09-23' '2024-09-24' '2024-09-25' '2024-09-26'
 '2024-09-27' '2024-09-28' '2024-09-29' '2024-09-30' '2024-10-01'
 '2024-10-02' '2024-10-03' '2024-10-04' '2024-10-05' '2024-10-06'
 '2024-10-07' '2024-10-08' '2024-10-09' '2024-10-10' '2024-10-11'
 '2024-10-12' '2024-10-13' '2024-10-14' '2024-10-15' '2024-10-16'
 '2024-10-17' '2024-10-18' '2024-10-19' '2024-10-20' '2024-10-21'
 '2024-10-22' '2024-10-23' '2024-10-24' '2024-10-25' '2024-10-26'
 '2024-10-27' '2024-10-28' '2024-10-29' '2024-10-30' '2024-10-31'
 '2024-11-01' '2024-11-02' '2024-11-03' '2024-11-04' '2024-11-05'
 '2024-11-06' '2024-11-07' '2024-11-08' '2024-11-09' '2024-11-10'
 '2024-11-11' '2024-11-12' '2024-11-13' '2024-11-14' '2024-11-15'
 '2024-11-16' '2024-11-17' '2024-11-18' '2024-11-19' '2024-11-20'
 '2024-11-21' '2024-11-22' '2024-11-23' '2024-11-24' '2024-11-25'
 '2024-11-26' '2024-11-27' '2024-11-28' '2024-11-29' '2024-11-30'
 '2024-12-01' '2024-12-02' '2024-12-03' '2024-12-04' '2024-12-05'
 '2024-12-06' '2024-12-07' '2024-12-08' '2024-12-09' '2024-12-10'
 '2024-12-11' '2024-12-12' '2024-12-13' '2024-12-14' '2024-12-15'
 '2024-12-16' '2024-12-17' '2024-12-18' '2024-12-19' '2024-12-20'
 '2024-12-21' '2024-12-22' '2024-12-23' '2024-12-24' '2024-12-25'
 '2024-12-26' '2024-12-27' '2024-12-28' '2024-12-29' '2024-12-30'
 '2024-12-31' '2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04'
 '2025-01-05' '2025-01-06' '2025-01-07' '2025-01-08' '2025-01-09'
 '2025-01-10' '2025-01-11' '2025-01-12' '2025-01-13' '2025-01-14'
 '2025-01-15' '2025-01-16' '2025-01-17' '2025-01-18' '2025-01-19'
 '2025-01-20' '2025-01-21' '2025-01-22' '2025-01-23' '2025-01-24'
 '2025-01-25' '2025-01-26' '2025-01-27' '2025-01-28' '2025-01-29'
 '2025-01-30' '2025-01-31' '2025-02-01' '2025-02-02' '2025-02-03'
 '2025-02-04' '2025-02-05' '2025-02-06' '2025-02-07' '2025-02-08'
 '2025-02-09' '2025-02-10' '2025-02-11' '2025-02-12' '2025-02-13'
 '2025-02-14' '2025-02-15' '2025-02-16' '2025-02-17' '2025-02-18'
 '2025-02-19' '2025-02-20' '2025-02-21' '2025-02-22' '2025-02-23'
 '2025-02-24' '2025-02-25' '2025-02-26' '2025-02-27' '2025-02-28'
 '2025-03-01' '2025-03-02' '2025-03-03' '2025-03-04' '2025-03-05'
 '2025-03-06' '2025-03-07' '2025-03-08' '2025-03-09' '2025-03-10'
 '2025-03-11' '2025-03-12' '2025-03-13' '2025-03-14' '2025-03-15'
 '2025-03-16' '2025-03-17' '2025-03-18' '2025-03-19' '2025-03-20'
 '2025-03-21' '2025-03-22' '2025-03-23' '2025-03-24' '2025-03-25'
 '2025-03-26' '2025-03-27' '2025-03-28' '2025-03-29' '2025-03-30'
 '2025-03-31' '2025-04-01' '2025-04-02' '2025-04-03' '2025-04-04'
 '2025-04-05' '2025-04-06' '2025-04-07' '2025-04-08' '2025-04-09'
 '2025-04-10' '2025-04-11' '2025-04-12' '2025-04-13' '2025-04-14'
 '2025-04-15' '2025-04-16' '2025-04-17' '2025-04-18' '2025-04-19'
 '2025-04-20' '2025-04-21' '2025-04-22' '2025-04-23' '2025-04-24'
 '2025-04-25' '2025-04-26' '2025-04-27' '2025-04-28' '2025-04-29'
 '2025-04-30' '2025-05-01' '2025-05-02' '2025-05-03' '2025-05-04'
 '2025-05-05' '2025-05-06' '2025-05-07' '2025-05-08' '2025-05-09'
 '2025-05-10' '2025-05-11' '2025-05-12' '2025-05-13' '2025-05-14'
 '2025-05-15' '2025-05-16' '2025-05-17' '2025-05-18' '2025-05-19'
 '2025-05-20' '2025-05-21' '2025-05-22' '2025-05-23' '2025-05-24'
 '2025-05-25' '2025-05-26' '2025-05-27' '2025-05-28' '2025-05-29'
 '2025-05-30' '2025-05-31' '2025-06-01' '2025-06-02' '2025-06-03'
 '2025-06-04' '2025-06-05' '2025-06-06' '2025-06-07' '2025-06-08'
 '2025-06-09' '2025-06-10' '2025-06-11' '2025-06-12' '2025-06-13'
 '2025-06-14' '2025-06-15' '2025-06-16' '2025-06-17' '2025-06-18'
 '2025-06-19' '2025-06-20' '2025-06-21' '2025-06-22' '2025-06-23'
 '2025-06-24' '2025-06-25' '2025-06-26' '2025-06-27' '2025-06-28'
 '2025-06-29' '2025-06-30' '2025-07-01' '2025-07-02' '2025-07-03'
 '2025-07-04' '2025-07-05' '2025-07-06' '2025-07-07' '2025-07-08'
 '2025-07-09' '2025-07-10' '2025-07-11' '2025-07-12' '2025-07-13'
 '2025-07-14' '2025-07-15' '2025-07-16' '2025-07-17' '2025-07-18'
 '2025-07-19' '2025-07-20' '2025-07-21' '2025-07-22' '2025-07-23'
 '2025-07-24' '2025-07-25' '2025-07-26' '2025-07-27' '2025-07-28'
 '2025-07-29' '2025-07-30' '2025-07-31' '2025-08-01' '2025-08-02'
 '2025-08-03' '2025-08-04' '2025-08-05' '2025-08-06' '2025-08-07'
 '2025-08-08' '2025-08-09' '2025-08-10' '2025-08-11' '2025-08-12'
 '2025-08-13' '2025-08-14' '2025-08-15' '2025-08-16' '2025-08-17'
 '2025-08-18' '2025-08-19' '2025-08-20' '2025-08-21' '2025-08-22'
 '2025-08-23' '2025-08-24' '2025-08-25' '2025-08-26' '2025-08-27'
 '2025-08-28' '2025-08-29' '2025-08-30' '2025-08-31' '2025-09-01'
 '2025-09-02' '2025-09-03' '2025-09-04' '2025-09-05' '2025-09-06'
 '2025-09-07' '2025-09-08' '2025-09-09' '2025-09-10' '2025-09-11'
 '2025-09-12' '2025-09-13' '2025-09-14' '2025-09-15' '2025-09-16'
 '2025-09-17' '2025-09-18' '2025-09-19' '2025-09-20' '2025-09-21'
 '2025-09-22' '2025-09-23' '2025-09-24' '2025-09-25' '2025-09-26'
 '2025-09-27' '2025-09-28' '2025-09-29' '2025-09-30' '2025-10-01'
 '2025-10-02' '2025-10-03' '2025-10-04' '2025-10-05' '2025-10-06'
 '2025-10-07' '2025-10-08' '2025-10-09' '2025-10-10' '2025-10-11'
 '2025-10-12' '2025-10-13' '2025-10-14' '2025-10-15' '2025-10-16'
 '2025-10-17' '2025-10-18' '2025-10-19' '2025-10-20' '2025-10-21'
 '2025-10-22' '2025-10-23' '2025-10-24' '2025-10-25' '2025-10-26'
 '2025-10-27' '2025-10-28' '2025-10-29' '2025-10-30' '2025-10-31'
 '2025-11-01' '2025-11-02' '2025-11-03' '2025-11-04' '2025-11-05'
 '2025-11-06' '2025-11-07' '2025-11-08' '2025-11-09' '2025-11-10'
 '2025-11-11' '2025-11-12' '2025-11-13' '2025-11-14' '2025-11-15'
 '2025-11-16' '2025-11-17' '2025-11-18' '2025-11-19' '2025-11-20'
 '2025-11-21' '2025-11-22' '2025-11-23' '2025-11-24' '2025-11-25'
 '2025-11-26' '2025-11-27' '2025-11-28' '2025-11-29' '2025-11-30'
 '2025-12-01' '2025-12-02' '2025-12-03' '2025-12-04' '2025-12-05'
 '2025-12-06' '2025-12-07' '2025-12-08' '2025-12-09' '2025-12-10'
 '2025-12-11' '2025-12-12' '2025-12-13' '2025-12-14' '2025-12-15'
 '2025-12-16' '2025-12-17' '2025-12-18' '2025-12-19' '2025-12-20'
 '2025-12-21' '2025-12-22' '2025-12-23' '2025-12-24' '2025-12-25'
 '2025-12-26' '2025-12-27' '2025-12-28' '2025-12-29' '2025-12-30'
 '2025-12-31']

hospital_id
['HHN-BIR-01' 'HHN-EDI-01' 'HHN-LON-01' 'HHN-LON-02' 'HHN-MAN-01']

ward
['Cardiology Ward' 'Day Case Unit' 'General Medicine Ward A'
 'General Medicine Ward B' 'ICU' 'Oncology Ward' 'Orthopaedics Ward A'
 'Orthopaedics Ward B']

staff_role
['Registered Nurse' 'Healthcare Assistant' 'Doctor'
 'Allied Health Professional']

planned_staff
[10  5  4  1  0  3  2  7  6  9 13  8 14]

actual_staff
[10  5  4  1  8  3  9  7  0  2  6 13 12 11 14]

safe_ratio_met
[ True False]

In [267]:
# Convert the date column to datetime format
sr["date"] = pd.to_datetime(sr["date"])

##### Feature Engineering

In [268]:
sr["staffing_year"] = sr["date"].dt.year
sr["staffing_month"] = sr["date"].dt.month_name()
sr["staffing_quarter"] = sr["date"].dt.quarter
sr["staffing_weekday"] = sr["date"].dt.day_name()

In [269]:
es["surgery_year"] = es["surgery_date"].dt.year
es["surgery_month"] = es["surgery_date"].dt.month_name()
es["surgery_quarter"] = es["surgery_date"].dt.quarter
es["surgery_weekday"] = es["surgery_date"].dt.day_name()

In [270]:
ad["admission_year"] = ad["admission_datetime"].dt.year
ad["admission_month"] = ad["admission_datetime"].dt.month_name()
ad["admission_quarter"] = ad["admission_datetime"].dt.quarter
ad["admission_weekday"] = ad["admission_datetime"].dt.day_name()
ad["admission_hour"] = ad["admission_datetime"].dt.hour

In [271]:
ad["discharge_year"] = ad["discharge_datetime"].dt.year
ad["discharge_month"] = ad["discharge_datetime"].dt.month_name()
ad["discharge_quarter"] = ad["discharge_datetime"].dt.quarter
ad["discharge_weekday"] = ad["discharge_datetime"].dt.day_name()
ad["discharge_hour"] = ad["discharge_datetime"].dt.hour

In [272]:
bd["bedding_year"] = bd["datetime"].dt.year
bd["bedding_month"] = bd["datetime"].dt.month_name()
bd["bedding_quarter"] = bd["datetime"].dt.quarter
bd["bedding_weekday"] = bd["datetime"].dt.day_name()
bd["bedding_hour"] = bd["datetime"].dt.hour

In [273]:
oa["arrival_year"] = oa["arrival_datetime"].dt.year
oa["arrival_month"] = oa["arrival_datetime"].dt.month_name()
oa["arrival_quarter"] = oa["arrival_datetime"].dt.quarter
oa["arrival_weekday"] = oa["arrival_datetime"].dt.day_name()
oa["arrival_hour"] = oa["arrival_datetime"].dt.hour

##### Normalisation Across Sources

In [274]:
set(ad["hospital_id"]) == set(hr["hospital_id"])
set(bd["hospital_id"]) == set(hr["hospital_id"])
set(oa["hospital_id"]) == set(hr["hospital_id"])
set(es["hospital_id"]) == set(hr["hospital_id"])
set(sr["hospital_id"]) == set(hr["hospital_id"])

True

In [275]:
ad["admission_datetime"] = ad["admission_datetime"].dt.normalize()
ad["discharge_datetime"] = ad["discharge_datetime"].dt.normalize()
bd["datetime"] = bd["datetime"].dt.normalize()
oa["arrival_datetime"] = oa["arrival_datetime"].dt.normalize()
es["surgery_date"] = es["surgery_date"].dt.normalize()

##### Save the cleaned datasets

In [ ]:
ad.to_csv("data/cleaned/admission_discharge_cleaned.csv", index=False)

bd.to_csv("data/cleaned/bed_inventory_cleaned.csv", index=False)

es.to_csv("data/cleaned/elective_surgery_cleaned.csv", index=False)

oa.to_csv("data/cleaned/outpatient_arrivals_cleaned.csv", index=False)

st.to_csv("data/cleaned/staffing_cleaned.csv", index=False)

hospital.to_csv("data/cleaned/hospital_information_cleaned.csv", index=False)

##### Aggregate each dataset to the daily level.

In [276]:
daily_admissions = (ad.groupby(["hospital_id", "admission_datetime"]).size().reset_index(name="total_admissions"))
daily_discharges = (ad.groupby(["hospital_id", "discharge_datetime"]).size().reset_index(name="total_discharges"))
daily_beds = (bd.groupby(["hospital_id", "datetime"]).agg({"total_beds": "first", "occupied_beds": "mean", "staffed_beds": "mean","closed_beds": "mean","occupancy_rate": "mean"}).reset_index())

In [277]:
completed = es[es["surgery_status"] == "Completed"]

daily_completed_surgeries = (completed.groupby(["hospital_id", "surgery_date"]).agg(completed_surgeries=("surgery_id", "count"),
                            expected_los=("expected_los_days", "mean")).reset_index())

In [278]:
cancelled = es[es["surgery_status"] == "Cancelled"]

daily_cancelled_surgeries = (cancelled.groupby(["hospital_id", "surgery_date"]).agg(cancelled_surgeries=("surgery_id", "count")).reset_index())

In [279]:
daily_staffing = sr.groupby(["hospital_id", "date"]).agg(planned_staff=("planned_staff", "sum"), actual_staff=("actual_staff", "sum"), safe_ratio=("safe_ratio_met", "mean")).reset_index()

In [280]:
daily_outpatients = (oa.groupby(["hospital_id", "arrival_datetime"]).agg(arrivals=("arrival_id", "count"),avg_time_to_admission=("time_to_admission", "mean"),bed_requests=("bed_requested", "sum")).reset_index()
)

##### Rename the date

In [281]:
daily_admissions = daily_admissions.rename(columns={"admission_datetime": "date"})
daily_discharges = daily_discharges.rename(columns={"discharge_datetime": "date"})
daily_beds = daily_beds.rename(columns={"datetime": "date"})
daily_outpatients = daily_outpatients.rename(columns={"arrival_datetime": "date"})
daily_completed_surgeries = daily_completed_surgeries.rename(columns={"surgery_date": "date"})
daily_cancelled_surgeries = daily_cancelled_surgeries.rename(columns={"surgery_date": "date"})

In [282]:
datasets = {
    "Admissions": daily_admissions,
    "Discharges": daily_discharges,
    "Beds": daily_beds,
    "Completed Surgeries": daily_completed_surgeries,
    "Cancelled Surgeries": daily_cancelled_surgeries,
    "Outpatients": daily_outpatients,
    "Staffing": daily_staffing,
}

for name, df in datasets.items():
    print(f"\n{name}")
    print("-" * 40)
    print(df.shape)
    print(df.head())
    print(df.info)

Admissions
----------------------------------------
(3659, 3)
  hospital_id       date  total_admissions
0  HHN-BIR-01 2024-01-01                20
1  HHN-BIR-01 2024-01-02                35
2  HHN-BIR-01 2024-01-03                29
3  HHN-BIR-01 2024-01-04                35
4  HHN-BIR-01 2024-01-05                41
<bound method DataFrame.info of      hospital_id       date  total_admissions
0     HHN-BIR-01 2024-01-01                20
1     HHN-BIR-01 2024-01-02                35
2     HHN-BIR-01 2024-01-03                29
3     HHN-BIR-01 2024-01-04                35
4     HHN-BIR-01 2024-01-05                41
...          ...        ...               ...
3654  HHN-MAN-01 2025-12-28                48
3655  HHN-MAN-01 2025-12-29                45
3656  HHN-MAN-01 2025-12-30                35
3657  HHN-MAN-01 2025-12-31                45
3658  HHN-MAN-01 2026-01-01                 5

[3659 rows x 3 columns]>

Discharges
----------------------------------------
(3728, 3)
  hospital_id       date  total_discharges
0  HHN-BIR-01 2024-01-02                 5
1  HHN-BIR-01 2024-01-03                17
2  HHN-BIR-01 2024-01-04                14
3  HHN-BIR-01 2024-01-05                29
4  HHN-BIR-01 2024-01-06                15
<bound method DataFrame.info of      hospital_id       date  total_discharges
0     HHN-BIR-01 2024-01-02                 5
1     HHN-BIR-01 2024-01-03                17
2     HHN-BIR-01 2024-01-04                14
3     HHN-BIR-01 2024-01-05                29
4     HHN-BIR-01 2024-01-06                15
...          ...        ...               ...
3723  HHN-MAN-01 2026-01-13                 1
3724  HHN-MAN-01 2026-01-14                 1
3725  HHN-MAN-01 2026-01-17                 2
3726  HHN-MAN-01 2026-02-03                 1
3727  HHN-MAN-01 2026-02-19                 1

[3728 rows x 3 columns]>

Beds
----------------------------------------
(3655, 7)
  hospital_id       date  total_beds  occupied_beds  staffed_beds  \
0  HHN-BIR-01 2024-01-01          42       1.083333     15.630208
1  HHN-BIR-01 2024-01-02          42       3.921875     15.578125
2  HHN-BIR-01 2024-01-03          42       6.864583     15.671875
3  HHN-BIR-01 2024-01-04          42       8.807292     15.578125
4  HHN-BIR-01 2024-01-05          42      10.312500     15.661458

   closed_beds  occupancy_rate
0          0.0        0.070894
1          0.0        0.269310
2          0.0        0.443168
3          0.0        0.576953
4          0.0        0.684849
<bound method DataFrame.info of      hospital_id       date  total_beds  occupied_beds  staffed_beds  \
0     HHN-BIR-01 2024-01-01          42       1.083333     15.630208
1     HHN-BIR-01 2024-01-02          42       3.921875     15.578125
2     HHN-BIR-01 2024-01-03          42       6.864583     15.671875
3     HHN-BIR-01 2024-01-04          42       8.807292     15.578125
4     HHN-BIR-01 2024-01-05          42      10.312500     15.661458
...          ...        ...         ...            ...           ...
3650  HHN-MAN-01 2025-12-27          24      16.505208     20.364583
3651  HHN-MAN-01 2025-12-28          24      15.947917     20.291667
3652  HHN-MAN-01 2025-12-29          24      16.291667     20.286458
3653  HHN-MAN-01 2025-12-30          24      16.786458     20.322917
3654  HHN-MAN-01 2025-12-31          24      16.307292     20.343750

      closed_beds  occupancy_rate
0             0.0        0.070894
1             0.0        0.269310
2             0.0        0.443168
3             0.0        0.576953
4             0.0        0.684849
...           ...             ...
3650          0.0        0.788102
3651          0.0        0.761725
3652          0.0        0.762066
3653          0.0        0.790120
3654          0.0        0.779643

[3655 rows x 7 columns]>

Completed Surgeries
----------------------------------------
(2522, 4)
  hospital_id       date  completed_surgeries  expected_los
0  HHN-BIR-01 2024-01-02                    3      1.966667
1  HHN-BIR-01 2024-01-03                    1      1.400000
2  HHN-BIR-01 2024-01-04                    8      2.975000
3  HHN-BIR-01 2024-01-05                   13      2.338462
4  HHN-BIR-01 2024-01-08                   12      2.566667
<bound method DataFrame.info of      hospital_id       date  completed_surgeries  expected_los
0     HHN-BIR-01 2024-01-02                    3      1.966667
1     HHN-BIR-01 2024-01-03                    1      1.400000
2     HHN-BIR-01 2024-01-04                    8      2.975000
3     HHN-BIR-01 2024-01-05                   13      2.338462
4     HHN-BIR-01 2024-01-08                   12      2.566667
...          ...        ...                  ...           ...
2517  HHN-MAN-01 2025-12-23                    3      2.933333
2518  HHN-MAN-01 2025-12-24                    4      3.300000
2519  HHN-MAN-01 2025-12-29                    5      3.500000
2520  HHN-MAN-01 2025-12-30                    6      2.916667
2521  HHN-MAN-01 2025-12-31                    3      3.700000

[2522 rows x 4 columns]>

Cancelled Surgeries
----------------------------------------
(1295, 3)
  hospital_id       date  cancelled_surgeries
0  HHN-BIR-01 2024-01-03                    1
1  HHN-BIR-01 2024-01-04                    1
2  HHN-BIR-01 2024-01-05                    1
3  HHN-BIR-01 2024-01-08                    1
4  HHN-BIR-01 2024-01-09                    1
<bound method DataFrame.info of      hospital_id       date  cancelled_surgeries
0     HHN-BIR-01 2024-01-03                    1
1     HHN-BIR-01 2024-01-04                    1
2     HHN-BIR-01 2024-01-05                    1
3     HHN-BIR-01 2024-01-08                    1
4     HHN-BIR-01 2024-01-09                    1
...          ...        ...                  ...
1290  HHN-MAN-01 2025-12-10                    3
1291  HHN-MAN-01 2025-12-11                    2
1292  HHN-MAN-01 2025-12-15                    1
1293  HHN-MAN-01 2025-12-19                    1
1294  HHN-MAN-01 2025-12-29                    2

[1295 rows x 3 columns]>

Outpatients
----------------------------------------
(3655, 5)
  hospital_id       date  arrivals  avg_time_to_admission  bed_requests
0  HHN-BIR-01 2024-01-01        80              30.550000            22
1  HHN-BIR-01 2024-01-02        83              43.831325            31
2  HHN-BIR-01 2024-01-03        72              49.944444            28
3  HHN-BIR-01 2024-01-04        95              58.431579            29
4  HHN-BIR-01 2024-01-05        80              56.000000            26
<bound method DataFrame.info of      hospital_id       date  arrivals  avg_time_to_admission  bed_requests
0     HHN-BIR-01 2024-01-01        80              30.550000            22
1     HHN-BIR-01 2024-01-02        83              43.831325            31
2     HHN-BIR-01 2024-01-03        72              49.944444            28
3     HHN-BIR-01 2024-01-04        95              58.431579            29
4     HHN-BIR-01 2024-01-05        80              56.000000            26
...          ...        ...       ...                    ...           ...
3650  HHN-MAN-01 2025-12-27       107              55.411215            36
3651  HHN-MAN-01 2025-12-28       170              49.941176            50
3652  HHN-MAN-01 2025-12-29       134              44.052239            40
3653  HHN-MAN-01 2025-12-30        98              37.795918            25
3654  HHN-MAN-01 2025-12-31       139              53.870504            44

[3655 rows x 5 columns]>

Staffing
----------------------------------------
(3655, 5)
  hospital_id       date  planned_staff  actual_staff  safe_ratio
0  HHN-BIR-01 2024-01-01             64            61     0.93750
1  HHN-BIR-01 2024-01-02             64            58     0.87500
2  HHN-BIR-01 2024-01-03             64            62     0.93750
3  HHN-BIR-01 2024-01-04             64            63     0.96875
4  HHN-BIR-01 2024-01-05             64            62     0.93750
<bound method DataFrame.info of      hospital_id       date  planned_staff  actual_staff  safe_ratio
0     HHN-BIR-01 2024-01-01             64            61     0.93750
1     HHN-BIR-01 2024-01-02             64            58     0.87500
2     HHN-BIR-01 2024-01-03             64            62     0.93750
3     HHN-BIR-01 2024-01-04             64            63     0.96875
4     HHN-BIR-01 2024-01-05             64            62     0.93750
...          ...        ...            ...           ...         ...
3650  HHN-MAN-01 2025-12-27             77            73     0.87500
3651  HHN-MAN-01 2025-12-28             77            75     0.87500
3652  HHN-MAN-01 2025-12-29             77            75     0.93750
3653  HHN-MAN-01 2025-12-30             77            75     0.93750
3654  HHN-MAN-01 2025-12-31             77            71     0.81250

[3655 rows x 5 columns]>

##### Merge everything

In [285]:
df = daily_admissions.copy()

df = df.merge(daily_discharges, on=["hospital_id", "date"], how="left")
df = df.merge(daily_beds, on=["hospital_id", "date"], how="left")
df = df.merge(daily_completed_surgeries,on=["hospital_id", "date"], how="left")
df = df.merge(daily_cancelled_surgeries, on=["hospital_id", "date"], how="left")
df = df.merge(daily_outpatients, on=["hospital_id", "date"], how="left")
df = df.merge(daily_staffing, on=["hospital_id", "date"], how="left")
df = df.merge(hr, on="hospital_id", how="left")

In [288]:
print("="*50)
print("Merge Dataset Overview")
print("="*50)

print("\nFirst 5 Rows:")
print(df.head())

print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")
print(f"Shape: {df.shape}")

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nUnique Values:")
print(df.nunique())

for col in df.columns:
    print(f"\n{col}")
    print(df[col].unique())

==================================================
Merge Dataset Overview
==================================================

First 5 Rows:
  hospital_id       date  total_admissions  total_discharges  total_beds  \
0  HHN-BIR-01 2024-01-01                20               NaN        42.0
1  HHN-BIR-01 2024-01-02                35               5.0        42.0
2  HHN-BIR-01 2024-01-03                29              17.0        42.0
3  HHN-BIR-01 2024-01-04                35              14.0        42.0
4  HHN-BIR-01 2024-01-05                41              29.0        42.0

   occupied_beds  staffed_beds  closed_beds  occupancy_rate  \
0       1.083333     15.630208          0.0        0.070894
1       3.921875     15.578125          0.0        0.269310
2       6.864583     15.671875          0.0        0.443168
3       8.807292     15.578125          0.0        0.576953
4      10.312500     15.661458          0.0        0.684849

   completed_surgeries  ...  avg_time_to_admission  bed_requests  \
0                  NaN  ...              30.550000          22.0
1                  3.0  ...              43.831325          31.0
2                  1.0  ...              49.944444          28.0
3                  8.0  ...              58.431579          29.0
4                 13.0  ...              56.000000          26.0

   planned_staff  actual_staff  safe_ratio       hospital_name        city  \
0           64.0          61.0     0.93750  Horizon Birmingham  Birmingham
1           64.0          58.0     0.87500  Horizon Birmingham  Birmingham
2           64.0          62.0     0.93750  Horizon Birmingham  Birmingham
3           64.0          63.0     0.96875  Horizon Birmingham  Birmingham
4           64.0          62.0     0.93750  Horizon Birmingham  Birmingham

     tier specialty_emphasis total_bed_capacity
0  Medium         Cardiology                126
1  Medium         Cardiology                126
2  Medium         Cardiology                126
3  Medium         Cardiology                126
4  Medium         Cardiology                126

[5 rows x 23 columns]
Rows: 3659
Columns: 23
Shape: (3659, 23)

Column Names:
['hospital_id', 'date', 'total_admissions', 'total_discharges', 'total_beds', 'occupied_beds', 'staffed_beds', 'closed_beds', 'occupancy_rate', 'completed_surgeries', 'expected_los', 'cancelled_surgeries', 'arrivals', 'avg_time_to_admission', 'bed_requests', 'planned_staff', 'actual_staff', 'safe_ratio', 'hospital_name', 'city', 'tier', 'specialty_emphasis', 'total_bed_capacity']

Data Types:
hospital_id                      object
date                     datetime64[ns]
total_admissions                  int64
total_discharges                float64
total_beds                      float64
occupied_beds                   float64
staffed_beds                    float64
closed_beds                     float64
occupancy_rate                  float64
completed_surgeries             float64
expected_los                    float64
cancelled_surgeries             float64
arrivals                        float64
avg_time_to_admission           float64
bed_requests                    float64
planned_staff                   float64
actual_staff                    float64
safe_ratio                      float64
hospital_name                    object
city                             object
tier                             object
specialty_emphasis               object
total_bed_capacity                int64
dtype: object

Missing Values:
hospital_id                 0
date                        0
total_admissions            0
total_discharges            2
total_beds                  4
occupied_beds               4
staffed_beds                4
closed_beds                 4
occupancy_rate              4
completed_surgeries      1137
expected_los             1137
cancelled_surgeries      2364
arrivals                    4
avg_time_to_admission       4
bed_requests                4
planned_staff               4
actual_staff                4
safe_ratio                  4
hospital_name               0
city                        0
tier                        0
specialty_emphasis          0
total_bed_capacity          0
dtype: int64

Duplicate Rows:
0

Unique Values:
hospital_id                 5
date                      732
total_admissions           93
total_discharges           84
total_beds                  5
occupied_beds            2195
staffed_beds              272
closed_beds                77
occupancy_rate           3655
completed_surgeries        26
expected_los             1324
cancelled_surgeries         5
arrivals                  235
avg_time_to_admission    3559
bed_requests               85
planned_staff              11
actual_staff               45
safe_ratio                 11
hospital_name               5
city                        4
tier                        3
specialty_emphasis          4
total_bed_capacity          5
dtype: int64

hospital_id
['HHN-BIR-01' 'HHN-EDI-01' 'HHN-LON-01' 'HHN-LON-02' 'HHN-MAN-01']

date
<DatetimeArray>
['2024-01-01 00:00:00', '2024-01-02 00:00:00', '2024-01-03 00:00:00',
 '2024-01-04 00:00:00', '2024-01-05 00:00:00', '2024-01-06 00:00:00',
 '2024-01-07 00:00:00', '2024-01-08 00:00:00', '2024-01-09 00:00:00',
 '2024-01-10 00:00:00',
 ...
 '2025-12-23 00:00:00', '2025-12-24 00:00:00', '2025-12-25 00:00:00',
 '2025-12-26 00:00:00', '2025-12-27 00:00:00', '2025-12-28 00:00:00',
 '2025-12-29 00:00:00', '2025-12-30 00:00:00', '2025-12-31 00:00:00',
 '2026-01-01 00:00:00']
Length: 732, dtype: datetime64[ns]

total_admissions
[ 20  35  29  41  46  27  34  25  40  18  43  39  37  47  51  44  32  31
  24  33  55  30  52  28  42  48  38  23  36  45  50  13  22  21  16  19
  14  17  15  12  26  54  11   9   6  53  58  65  59  49  66   3  10   8
   7   5  64  69  77  56  57  67  63  70  81  75  79  62  72  84  82  74
  89  68  97  71  78  86  61  73  80 105  60  76  83  95  99  90 101 104
  85  91   4]

total_discharges
[nan  5. 17. 14. 29. 15. 26. 40. 30. 46. 32. 27. 25. 44. 31. 43. 36. 35.
 34. 51. 24. 45. 38. 28. 39. 47. 23. 37. 42. 50. 41. 20. 21. 33. 22. 19.
 48. 16. 12. 18. 49. 52.  9. 13.  3. 11. 10.  8.  7.  6. 60. 57. 61. 62.
 64. 69. 71. 79. 67. 76. 53. 54. 74. 68. 56. 65. 73. 75. 59. 58. 66. 77.
 78. 89. 63. 70. 86. 55. 80. 83. 81. 87. 85. 72.  1.]

total_beds
[42. nan 16. 38. 18. 24.]

occupied_beds
[ 1.08333333  3.921875    6.86458333 ... 15.28645833 16.65625
 16.88541667]

staffed_beds
[15.63020833 15.578125   15.671875   15.66145833 15.52604167 15.546875
 15.59375    15.64583333 15.53645833 15.61979167 15.61458333 15.56770833
 15.54166667 15.63541667 15.59895833 15.60416667 15.65625    15.58854167
 15.52083333 15.625      15.609375   15.55208333 15.67708333 15.58333333
 15.55729167 15.5625     15.640625   15.69791667 15.68229167 15.703125
 15.66666667 15.65104167 15.71354167 15.6875     15.71875    15.69270833
 15.72395833 15.70833333 15.72916667 15.5        15.734375   15.57291667
 15.53125    15.49479167 15.44270833 15.515625   15.46354167 15.453125
         nan 11.61979167 11.671875   11.6875     11.65625    11.65104167
 11.59375    11.66145833 11.63541667 11.56770833 11.63020833 11.67708333
 11.58333333 11.609375   11.55208333 11.640625   11.66666667 11.61458333
 11.625      11.59895833 11.578125   11.68229167 11.60416667 11.71354167
 11.703125   11.734375   11.72395833 11.69791667 11.70833333 11.69270833
 11.64583333 11.71875    11.72916667 11.58854167 11.5625     11.57291667
 11.53645833 11.55729167 27.74479167 27.71354167 27.92708333 27.82291667
 27.75       27.72916667 27.6875     27.89583333 27.83854167 27.796875
 27.828125   27.609375   27.67708333 27.80208333 27.76041667 27.64583333
 27.77604167 27.85416667 27.765625   27.77083333 27.78125    27.83333333
 27.72395833 27.75520833 27.50520833 27.71875    27.8125     27.81770833
 27.79166667 27.66666667 27.59375    27.63020833 27.73958333 27.890625
 27.640625   27.86458333 27.80729167 27.69270833 27.671875   27.69791667
 27.91145833 27.84895833 27.90104167 27.875      27.88020833 27.94791667
 27.58333333 27.921875   27.84375    27.93229167 27.91666667 27.68229167
 27.86979167 27.953125   27.96354167 27.859375   27.9375     27.90625
 27.94270833 27.70833333 27.703125   27.88541667 27.65625    27.78645833
 27.95833333 27.97916667 27.66145833 27.734375   27.65104167 27.63541667
 27.58854167 27.578125   27.97395833 27.96875    27.52083333 27.61979167
 18.88020833 18.86458333 18.66145833 18.77604167 18.828125   18.78125
 18.77083333 18.83333333 18.89583333 18.875      18.90625    18.79166667
 18.81770833 18.84895833 18.859375   18.76041667 18.86979167 18.72916667
 18.88541667 18.84375    18.83854167 18.80729167 18.92708333 18.796875
 18.71875    18.80208333 18.91145833 18.78645833 18.94270833 18.921875
 18.64583333 18.734375   18.75520833 18.90104167 18.95833333 18.890625
 18.85416667 18.93229167 18.96875    18.9375     18.94791667 18.953125
 18.91666667 18.82291667 18.97916667 18.96354167 18.8125     18.97395833
 18.984375   18.765625   18.74479167 18.73958333 18.69791667 20.35416667
 20.36458333 20.33854167 20.34895833 20.265625   20.11979167 20.359375
 20.31770833 20.3125     20.20833333 20.36979167 20.25520833 20.24479167
 20.296875   20.375      20.328125   20.234375   20.21875    20.28645833
 20.27604167 20.30208333 20.26041667 20.29166667 20.34375    20.30729167
 20.23958333 20.421875   20.390625   20.40104167 20.33333333 20.38541667
 20.40625    20.42708333 20.38020833 20.44791667 20.41666667 20.41145833
 20.44270833 20.43229167 20.46875    20.4375     20.32291667 20.27083333
 20.28125    20.46354167 20.39583333 20.45833333 20.21354167 20.22916667
 20.453125   20.25       20.47395833 20.140625   20.13541667 20.171875
 20.22395833 20.203125   20.484375  ]

closed_beds
[0.         0.125      0.25       0.21875    0.00520833 0.10416667
 0.16666667 0.14583333 0.02083333 0.109375   0.04166667 0.1875
 0.375      0.03125    0.19791667 0.05208333 0.07291667 0.22395833
 0.234375   0.05729167 0.03645833 0.015625   0.38020833 0.93229167
 0.875      0.69270833 0.41666667 0.625      0.49479167        nan
 0.09375    0.08854167 0.22916667 0.328125   0.29166667 0.01041667
 0.203125   0.11458333 0.0625     0.02604167 0.08333333 0.15625
 0.09895833 0.11979167 0.06770833 0.34895833 0.3125     0.265625
 0.078125   0.36458333 0.5        0.765625   0.6875     0.4375
 0.75       0.53125    0.52083333 0.66666667 0.13020833 0.38541667
 0.171875   0.34375    0.59895833 0.33854167 0.046875   0.20833333
 0.17708333 0.27083333 0.28125    0.390625   0.59375    0.83333333
 1.         0.140625   0.13541667 0.47916667 0.39583333 0.45833333]

occupancy_rate
[0.07089359 0.26930979 0.44316829 ... 0.76206582 0.79011987 0.77964271]

completed_surgeries
[nan  3.  1.  8. 13. 12.  6. 11.  4. 14. 10.  5.  9.  7. 17.  2. 15. 20.
 18. 16. 19. 23. 22. 21. 24. 25. 26.]

expected_los
[       nan 1.96666667 1.4        ... 3.31111111 2.87222222 4.95      ]

cancelled_surgeries
[nan  1.  3.  2.  4.  5.]

arrivals
[ 80.  83.  72.  95.  98.  69. 119.  92.  82. 114. 111.  88.  97. 128.
 121. 101. 122. 107.  62.  87.  84. 141. 137.  55. 164.  94.  86.  59.
 104. 116.  70. 167.  99. 134.  71. 124. 117. 109.  68.  81.  51.  96.
  89. 139.  79.  47.  63.  44. 162.  78.  41. 115.  85.  75.  77. 149.
  36.  56.  93. 131. 125.  91.  53. 159.  54.  52.  58. 102.  61. 136.
 118.  73.  76.  66. 120.  67.  45.  49.  74.  64. 110.  42.  57. 123.
  40.  38.  50.  35.  43.  60.  48.  26.  31.  65. 100.  33. 132. 154.
 127.  46. 103.  90. 126. 144. 146. 129. 133. 222. 113. 152. 143. 135.
 108. 153. 105. 112. 106.  39.  30.  37.  24. 138. 201. 147.  nan  19.
  22.  32.  25.  29.  27.  34. 157.  28.  23. 225. 197. 209. 171. 161.
 223. 184. 185. 186. 216. 242. 231. 193. 212. 183. 172. 174. 182. 190.
 194. 229. 246. 233. 191. 238. 221. 175. 176. 163. 188. 251. 314. 227.
 211. 169. 155. 276. 142. 204. 196. 177. 243. 239. 180. 198. 244. 160.
 213. 148. 205. 294. 236. 130. 140. 150. 145. 156. 166. 192. 179. 228.
 158. 173. 206. 170. 189. 219. 218. 215. 195. 262. 187. 178. 210. 226.
 241. 289. 168. 291. 315. 255. 329. 257. 277. 278. 202. 247. 181. 200.
 253. 165. 151. 258. 203. 270. 208. 234. 224. 284. 199. 217.]

avg_time_to_admission
[30.55       43.8313253  49.94444444 ... 44.05223881 37.79591837
 53.8705036 ]

bed_requests
[ 22.  31.  28.  29.  26.  39.  18.  36.  21.  23.  33.  45.  25.  30.
  35.  42.  27.  48.  34.  24.  47.  20.  55.  19.  38.  50.  40.  16.
  32.  44.  41.  12.  11.  49.  15.  37.  13.  14.  17.   9.  10.   7.
   8.   5.   6.  43.  54.  52.  63.  51.  46.  53.  57.  nan   4.  71.
  60.  72.  59.  61.  87.  73.  58.  67.  66.  64.  69.  79.  65.  99.
  68.  56.  91.  62.  76.  75.  70.  74.  78.  88.  82. 103.  86.  97.
  85.  80.]

planned_staff
[ 64.  63.  nan  48.  47.  46. 114. 113. 112.  79.  78.  77.]

actual_staff
[ 61.  58.  62.  63.  64.  60.  59.  57.  55.  56.  53.  nan  48.  47.
  46.  45.  44.  41.  42.  43. 114. 111. 110. 109. 113. 106. 105. 112.
 108. 107. 102. 104. 103. 101.  71.  73.  77.  78.  79.  72.  76.  74.
  70.  75.  66.  69.]

safe_ratio
[0.9375  0.875   0.96875 1.      0.84375 0.90625 0.8125  0.78125 0.75
     nan 0.6875  0.71875]

hospital_name
['Horizon Birmingham' 'Horizon Edinburgh' 'Horizon London Central'
 'Horizon Riverside' 'Horizon Manchester']

city
['Birmingham' 'Edinburgh' 'London' 'Manchester']

tier
['Medium' 'Flagship' 'Large']

specialty_emphasis
['Cardiology' 'General' 'Oncology' 'Orthopaedics']

total_bed_capacity
[126  94 224 152 164]

##### Replace the nan

In [289]:
df["completed_surgeries"] = df["completed_surgeries"].fillna(0)

df["cancelled_surgeries"] = df["cancelled_surgeries"].fillna(0)

df["total_discharges"] = df["total_discharges"].fillna(0)

df.loc[df["completed_surgeries"] == 0, "expected_los"] = 0

In [290]:
df[df.isna().any(axis=1)]

,hospital_id,date,total_admissions,total_discharges,total_beds,occupied_beds,staffed_beds,closed_beds,occupancy_rate,completed_surgeries,...,avg_time_to_admission,bed_requests,planned_staff,actual_staff,safe_ratio,hospital_name,city,tier,specialty_emphasis,total_bed_capacity
731,HHN-BIR-01,2026-01-01,3,35.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,Horizon Birmingham,Birmingham,Medium,Cardiology,126
2194,HHN-LON-01,2026-01-01,4,57.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,Horizon London Central,London,Flagship,General,224
2926,HHN-LON-02,2026-01-01,4,45.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,Horizon Riverside,London,Large,Oncology,152
3658,HHN-MAN-01,2026-01-01,5,37.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,Horizon Manchester,Manchester,Large,Orthopaedics,164